// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/36       [336420]
Creator        : ajperch
Date           : Tue Jun 28 10:45:26 2016
Host           : Linux buildvm-19.phx2.fedoraproject.org 4.3.5-300.fc23.x86_64 #1 SMP Mon Feb 1 03:18:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /unix/fnu/ajperch/CHIPS/SpeedupFitter/WCSimAnalysis/tmva
Training events: 3469
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
deltaCharge2LnL               deltaCharge2LnL               deltaCharge2LnL               deltaCharge2LnL                                                 'F'    [-19017.2089844,14292.9570312]
deltaTime2LnL                 deltaTime2LnL                 deltaTime2LnL                 deltaTime2LnL                                                   'F'    [-8358.29003906,20050.8886719]
fracQOutsideRing_mu           fracQOutsideRing_mu           fracQOutsideRing_mu           fracQOutsideRing_mu                                             'F'    [0,1]
fracPredQOutsideRing_mu       fracPredQOutsideRing_mu       fracPredQOutsideRing_mu       fracPredQOutsideRing_mu                                         'F'    [0.0781822949648,1]
predictedChargeOverTotalCharge_mu predictedChargeOverTotalCharge_mu predictedChargeOverTotalCharge_mu predictedChargeOverTotalCharge_mu                                       'F'    [0.244273379445,17.6130828857]
predictedChargeOverTotalCharge_el predictedChargeOverTotalCharge_el predictedChargeOverTotalCharge_el predictedChargeOverTotalCharge_el                                       'F'    [-999.900024414,19.610004425]
nHits                         nHits                         nHits                         nHits                                                           'F'    [64,8301]
recoE_el/totalQ               recoE_el_D_totalQ             recoE_el/totalQ               recoE_el/totalQ                                                 'F'    [0.07718577981,29.6625461578]
recoE_mu/totalQ               recoE_mu_D_totalQ             recoE_mu/totalQ               recoE_mu/totalQ                                                 'F'    [0.0903712287545,7.82976579666]
charge2LnL_el/nHits           chargeLikelihoodRatio_el      chargeLikelihoodRatio_el      chargeLikelihoodRatio_el                                        'F'    [0,46.2674369812]
charge2LnL_mu/nHits           chargeLikelihoodRatio_mu      chargeLikelihoodRatio_mu      chargeLikelihoodRatio_mu                                        'F'    [5.23294067383,48.2155036926]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "deltaCharge2LnL", "deltaTime2LnL", "fracQOutsideRing_mu", "fracPredQOutsideRing_mu", "predictedChargeOverTotalCharge_mu", "predictedChargeOverTotalCharge_el", "nHits", "recoE_el/totalQ", "recoE_mu/totalQ", "charge2LnL_el/nHits", "charge2LnL_mu/nHits" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.260326586958629;
   fWeightMatrix0to1[1][0] = 2.0025663379751;
   fWeightMatrix0to1[2][0] = 1.67955402600983;
   fWeightMatrix0to1[3][0] = 2.09223263458949;
   fWeightMatrix0to1[4][0] = -1.9101592063311;
   fWeightMatrix0to1[5][0] = -8.75045893945697;
   fWeightMatrix0to1[6][0] = -0.786911289406849;
   fWeightMatrix0to1[7][0] = 1.92598973364039;
   fWeightMatrix0to1[8][0] = -1.5185175660289;
   fWeightMatrix0to1[9][0] = -1.67394630144358;
   fWeightMatrix0to1[10][0] = -1.53855943202076;
   fWeightMatrix0to1[11][0] = -0.3511577360284;
   fWeightMatrix0to1[12][0] = -1.41338467044228;
   fWeightMatrix0to1[13][0] = -0.521088509498562;
   fWeightMatrix0to1[14][0] = -0.613787618193064;
   fWeightMatrix0to1[15][0] = 0.578529743041389;
   fWeightMatrix0to1[0][1] = 0.0547143251494593;
   fWeightMatrix0to1[1][1] = 2.06377740614005;
   fWeightMatrix0to1[2][1] = -0.0689341210608794;
   fWeightMatrix0to1[3][1] = 1.35450256317814;
   fWeightMatrix0to1[4][1] = -0.0993202486949444;
   fWeightMatrix0to1[5][1] = -0.698314714429239;
   fWeightMatrix0to1[6][1] = 0.737016361703125;
   fWeightMatrix0to1[7][1] = 0.0797099071581158;
   fWeightMatrix0to1[8][1] = -1.09354866763566;
   fWeightMatrix0to1[9][1] = 0.0858147441336397;
   fWeightMatrix0to1[10][1] = 1.47542046480336;
   fWeightMatrix0to1[11][1] = -0.895453745138473;
   fWeightMatrix0to1[12][1] = -1.33236334333835;
   fWeightMatrix0to1[13][1] = 0.402580814659425;
   fWeightMatrix0to1[14][1] = 0.673306964862905;
   fWeightMatrix0to1[15][1] = 1.56578837408922;
   fWeightMatrix0to1[0][2] = -0.871774998571585;
   fWeightMatrix0to1[1][2] = -0.282021433945263;
   fWeightMatrix0to1[2][2] = 0.866996608523594;
   fWeightMatrix0to1[3][2] = -0.458879893743369;
   fWeightMatrix0to1[4][2] = -1.58150792379429;
   fWeightMatrix0to1[5][2] = 4.26495313846105;
   fWeightMatrix0to1[6][2] = -1.2142849241794;
   fWeightMatrix0to1[7][2] = 1.07440216651488;
   fWeightMatrix0to1[8][2] = 1.07040442134337;
   fWeightMatrix0to1[9][2] = 0.073594382498627;
   fWeightMatrix0to1[10][2] = 1.98411839831161;
   fWeightMatrix0to1[11][2] = 0.451918216843854;
   fWeightMatrix0to1[12][2] = -0.824004856380771;
   fWeightMatrix0to1[13][2] = -0.935243919841689;
   fWeightMatrix0to1[14][2] = 0.878089088702563;
   fWeightMatrix0to1[15][2] = -0.248751031999048;
   fWeightMatrix0to1[0][3] = 1.40813451650896;
   fWeightMatrix0to1[1][3] = 1.25056369636145;
   fWeightMatrix0to1[2][3] = 1.73100826967425;
   fWeightMatrix0to1[3][3] = 0.0490137610108968;
   fWeightMatrix0to1[4][3] = -1.66346079333605;
   fWeightMatrix0to1[5][3] = -0.611833048245879;
   fWeightMatrix0to1[6][3] = -1.82949802899237;
   fWeightMatrix0to1[7][3] = -0.874047577664969;
   fWeightMatrix0to1[8][3] = -1.2963638203804;
   fWeightMatrix0to1[9][3] = -1.64230504951637;
   fWeightMatrix0to1[10][3] = 1.45251285172441;
   fWeightMatrix0to1[11][3] = 0.785216912821021;
   fWeightMatrix0to1[12][3] = -2.09476239022104;
   fWeightMatrix0to1[13][3] = 0.452395562822012;
   fWeightMatrix0to1[14][3] = -0.372187310379578;
   fWeightMatrix0to1[15][3] = 0.621847693178152;
   fWeightMatrix0to1[0][4] = 2.44775378874012;
   fWeightMatrix0to1[1][4] = 0.372317045432156;
   fWeightMatrix0to1[2][4] = 0.394355947230163;
   fWeightMatrix0to1[3][4] = -1.36283426634786;
   fWeightMatrix0to1[4][4] = 0.829152756832107;
   fWeightMatrix0to1[5][4] = -0.618395034421682;
   fWeightMatrix0to1[6][4] = -0.729056928261351;
   fWeightMatrix0to1[7][4] = -1.34530540685637;
   fWeightMatrix0to1[8][4] = 0.87674898183986;
   fWeightMatrix0to1[9][4] = 0.874028358278625;
   fWeightMatrix0to1[10][4] = 1.16415619382908;
   fWeightMatrix0to1[11][4] = 0.400177287013897;
   fWeightMatrix0to1[12][4] = -2.24075081759187;
   fWeightMatrix0to1[13][4] = -1.49551142895364;
   fWeightMatrix0to1[14][4] = 0.960531016392562;
   fWeightMatrix0to1[15][4] = 0.411747430001226;
   fWeightMatrix0to1[0][5] = 1.2018818597401;
   fWeightMatrix0to1[1][5] = 0.125905391390563;
   fWeightMatrix0to1[2][5] = 0.736881355177917;
   fWeightMatrix0to1[3][5] = -0.307241005412356;
   fWeightMatrix0to1[4][5] = -1.74106669518068;
   fWeightMatrix0to1[5][5] = 0.336333292633506;
   fWeightMatrix0to1[6][5] = 1.17342713786883;
   fWeightMatrix0to1[7][5] = -1.19378011830229;
   fWeightMatrix0to1[8][5] = -1.69687938472545;
   fWeightMatrix0to1[9][5] = -1.59083485666856;
   fWeightMatrix0to1[10][5] = -0.595469493369073;
   fWeightMatrix0to1[11][5] = 0.252021730257104;
   fWeightMatrix0to1[12][5] = 1.51868871638854;
   fWeightMatrix0to1[13][5] = -2.26403768818111;
   fWeightMatrix0to1[14][5] = -0.869338778428583;
   fWeightMatrix0to1[15][5] = 1.66865208749193;
   fWeightMatrix0to1[0][6] = -0.43325814988065;
   fWeightMatrix0to1[1][6] = -1.05821129835639;
   fWeightMatrix0to1[2][6] = -0.438038900586417;
   fWeightMatrix0to1[3][6] = 0.621667023016875;
   fWeightMatrix0to1[4][6] = -1.28071416426362;
   fWeightMatrix0to1[5][6] = -1.06351354592233;
   fWeightMatrix0to1[6][6] = 0.709931079693118;
   fWeightMatrix0to1[7][6] = 1.71726418306117;
   fWeightMatrix0to1[8][6] = -0.839812004907975;
   fWeightMatrix0to1[9][6] = 0.785578801959051;
   fWeightMatrix0to1[10][6] = -0.896809665997442;
   fWeightMatrix0to1[11][6] = -0.488789566975313;
   fWeightMatrix0to1[12][6] = -0.593653263177971;
   fWeightMatrix0to1[13][6] = 0.313329294931261;
   fWeightMatrix0to1[14][6] = -1.74149210983932;
   fWeightMatrix0to1[15][6] = 0.269603805352084;
   fWeightMatrix0to1[0][7] = 1.35020092783966;
   fWeightMatrix0to1[1][7] = 1.00731408884316;
   fWeightMatrix0to1[2][7] = -1.05679160405315;
   fWeightMatrix0to1[3][7] = 1.62487538600169;
   fWeightMatrix0to1[4][7] = 0.353687416919518;
   fWeightMatrix0to1[5][7] = -1.34360709053592;
   fWeightMatrix0to1[6][7] = 0.792544451592774;
   fWeightMatrix0to1[7][7] = -0.985772119957669;
   fWeightMatrix0to1[8][7] = -1.56486979764312;
   fWeightMatrix0to1[9][7] = -0.0345241973828701;
   fWeightMatrix0to1[10][7] = -0.10075379916434;
   fWeightMatrix0to1[11][7] = 1.82347133762693;
   fWeightMatrix0to1[12][7] = 0.916211252600508;
   fWeightMatrix0to1[13][7] = 0.698468951693565;
   fWeightMatrix0to1[14][7] = -0.31016018101299;
   fWeightMatrix0to1[15][7] = -0.00158102845794887;
   fWeightMatrix0to1[0][8] = -0.680076390843641;
   fWeightMatrix0to1[1][8] = 1.48917385921948;
   fWeightMatrix0to1[2][8] = -0.367897043634927;
   fWeightMatrix0to1[3][8] = -1.88169155296618;
   fWeightMatrix0to1[4][8] = 0.536532300709693;
   fWeightMatrix0to1[5][8] = -0.892773445531313;
   fWeightMatrix0to1[6][8] = 0.0767519737578645;
   fWeightMatrix0to1[7][8] = 1.28498136924637;
   fWeightMatrix0to1[8][8] = 1.81501689446283;
   fWeightMatrix0to1[9][8] = -2.02474223200228;
   fWeightMatrix0to1[10][8] = 0.367379509899417;
   fWeightMatrix0to1[11][8] = 1.99430670615036;
   fWeightMatrix0to1[12][8] = 1.45357334841105;
   fWeightMatrix0to1[13][8] = 0.692053569110447;
   fWeightMatrix0to1[14][8] = -1.45356466135939;
   fWeightMatrix0to1[15][8] = -0.28807969057333;
   fWeightMatrix0to1[0][9] = -1.88962345206691;
   fWeightMatrix0to1[1][9] = 1.40948601473417;
   fWeightMatrix0to1[2][9] = 1.48982511513719;
   fWeightMatrix0to1[3][9] = -1.09514614407619;
   fWeightMatrix0to1[4][9] = 0.00266591176798807;
   fWeightMatrix0to1[5][9] = -1.29363668525692;
   fWeightMatrix0to1[6][9] = -1.32966215553952;
   fWeightMatrix0to1[7][9] = 0.658817669296513;
   fWeightMatrix0to1[8][9] = 1.6744377612206;
   fWeightMatrix0to1[9][9] = -0.582697823521356;
   fWeightMatrix0to1[10][9] = -0.494505782175196;
   fWeightMatrix0to1[11][9] = 0.912899340153247;
   fWeightMatrix0to1[12][9] = 1.05480388710862;
   fWeightMatrix0to1[13][9] = 0.210327357519987;
   fWeightMatrix0to1[14][9] = 0.905870486774466;
   fWeightMatrix0to1[15][9] = -1.44037588322339;
   fWeightMatrix0to1[0][10] = 1.10187719738091;
   fWeightMatrix0to1[1][10] = 0.779277311047368;
   fWeightMatrix0to1[2][10] = -0.0187875288584442;
   fWeightMatrix0to1[3][10] = 0.0389079149920819;
   fWeightMatrix0to1[4][10] = 1.22539122065524;
   fWeightMatrix0to1[5][10] = 2.40949726091384;
   fWeightMatrix0to1[6][10] = -0.602221061947244;
   fWeightMatrix0to1[7][10] = 1.11768943385184;
   fWeightMatrix0to1[8][10] = -1.00598151772399;
   fWeightMatrix0to1[9][10] = -0.275444227074778;
   fWeightMatrix0to1[10][10] = 1.80605437426233;
   fWeightMatrix0to1[11][10] = 1.39939217607241;
   fWeightMatrix0to1[12][10] = 0.0803363579941489;
   fWeightMatrix0to1[13][10] = 1.64137561311322;
   fWeightMatrix0to1[14][10] = 1.86601676495211;
   fWeightMatrix0to1[15][10] = -1.97584926984456;
   fWeightMatrix0to1[0][11] = -0.188060484126958;
   fWeightMatrix0to1[1][11] = -0.408645720413737;
   fWeightMatrix0to1[2][11] = 0.191760822380932;
   fWeightMatrix0to1[3][11] = -1.41602864071921;
   fWeightMatrix0to1[4][11] = -2.20022972610279;
   fWeightMatrix0to1[5][11] = 1.17616226480457;
   fWeightMatrix0to1[6][11] = 1.80906955690029;
   fWeightMatrix0to1[7][11] = -1.8301839328222;
   fWeightMatrix0to1[8][11] = -0.325422290361105;
   fWeightMatrix0to1[9][11] = -0.344142792975375;
   fWeightMatrix0to1[10][11] = 0.128997925633346;
   fWeightMatrix0to1[11][11] = 1.47144039802066;
   fWeightMatrix0to1[12][11] = -0.301072168749686;
   fWeightMatrix0to1[13][11] = -0.782882628659756;
   fWeightMatrix0to1[14][11] = -1.08167525833462;
   fWeightMatrix0to1[15][11] = 1.15730370900139;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.706853995226943;
   fWeightMatrix1to2[0][1] = 1.04856990790703;
   fWeightMatrix1to2[0][2] = -0.45624492870918;
   fWeightMatrix1to2[0][3] = 0.316840058844206;
   fWeightMatrix1to2[0][4] = -1.06414807993558;
   fWeightMatrix1to2[0][5] = 0.710440537330994;
   fWeightMatrix1to2[0][6] = 0.119301327492293;
   fWeightMatrix1to2[0][7] = -0.309985898491279;
   fWeightMatrix1to2[0][8] = 0.00994010187248298;
   fWeightMatrix1to2[0][9] = -0.368467931518971;
   fWeightMatrix1to2[0][10] = 0.295142438343648;
   fWeightMatrix1to2[0][11] = -1.08199730972457;
   fWeightMatrix1to2[0][12] = 0.505071051268209;
   fWeightMatrix1to2[0][13] = 1.01860876469999;
   fWeightMatrix1to2[0][14] = 0.1245508705964;
   fWeightMatrix1to2[0][15] = -0.201461508687505;
   fWeightMatrix1to2[0][16] = 0.644053876736698;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -16716.9316406;
   fMax_1[0][0] = 1407.20666504;
   fMin_1[1][0] = -19017.2089844;
   fMax_1[1][0] = 14292.9570312;
   fMin_1[2][0] = -19017.2089844;
   fMax_1[2][0] = 14292.9570312;
   fMin_1[0][1] = -8358.29003906;
   fMax_1[0][1] = 7772.99316406;
   fMin_1[1][1] = -5819.78320312;
   fMax_1[1][1] = 20050.8886719;
   fMin_1[2][1] = -8358.29003906;
   fMax_1[2][1] = 20050.8886719;
   fMin_1[0][2] = 0.0325821451843;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = 0.0887037888169;
   fMax_1[0][3] = 0.979899227619;
   fMin_1[1][3] = 0.0781822949648;
   fMax_1[1][3] = 1;
   fMin_1[2][3] = 0.0781822949648;
   fMax_1[2][3] = 1;
   fMin_1[0][4] = 0.244273379445;
   fMax_1[0][4] = 14.9202194214;
   fMin_1[1][4] = 0.26649159193;
   fMax_1[1][4] = 17.6130828857;
   fMin_1[2][4] = 0.244273379445;
   fMax_1[2][4] = 17.6130828857;
   fMin_1[0][5] = -999.900024414;
   fMax_1[0][5] = 7.81826734543;
   fMin_1[1][5] = -999.900024414;
   fMax_1[1][5] = 19.610004425;
   fMin_1[2][5] = -999.900024414;
   fMax_1[2][5] = 19.610004425;
   fMin_1[0][6] = 83;
   fMax_1[0][6] = 8301;
   fMin_1[1][6] = 64;
   fMax_1[1][6] = 6114;
   fMin_1[2][6] = 64;
   fMax_1[2][6] = 8301;
   fMin_1[0][7] = 0.110606491566;
   fMax_1[0][7] = 29.6625461578;
   fMin_1[1][7] = 0.07718577981;
   fMax_1[1][7] = 10.9551029205;
   fMin_1[2][7] = 0.07718577981;
   fMax_1[2][7] = 29.6625461578;
   fMin_1[0][8] = 0.101162150502;
   fMax_1[0][8] = 5.56668233871;
   fMin_1[1][8] = 0.0903712287545;
   fMax_1[1][8] = 7.82976579666;
   fMin_1[2][8] = 0.0903712287545;
   fMax_1[2][8] = 7.82976579666;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 25.2747039795;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 46.2674369812;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 46.2674369812;
   fMin_1[0][10] = 6.21251344681;
   fMax_1[0][10] = 36.6185951233;
   fMin_1[1][10] = 5.23294067383;
   fMax_1[1][10] = 48.2155036926;
   fMin_1[2][10] = 5.23294067383;
   fMax_1[2][10] = 48.2155036926;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
