// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/36       [336420]
Creator        : ajperch
Date           : Mon Jun 27 11:21:30 2016
Host           : Linux buildvm-19.phx2.fedoraproject.org 4.3.5-300.fc23.x86_64 #1 SMP Mon Feb 1 03:18:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /unix/fnu/ajperch/CHIPS/SpeedupFitter/WCSimAnalysis/tmva
Training events: 3473
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 11
deltaCharge2LnL               deltaCharge2LnL               deltaCharge2LnL               deltaCharge2LnL                                                 'F'    [-16716.9316406,1986.66943359]
deltaTime2LnL                 deltaTime2LnL                 deltaTime2LnL                 deltaTime2LnL                                                   'F'    [-10892.2509766,7772.99316406]
fracQOutsideRing_mu           fracQOutsideRing_mu           fracQOutsideRing_mu           fracQOutsideRing_mu                                             'F'    [0,1]
fracPredQOutsideRing_mu       fracPredQOutsideRing_mu       fracPredQOutsideRing_mu       fracPredQOutsideRing_mu                                         'F'    [0.0803388804197,1]
predictedChargeOverTotalCharge_mu predictedChargeOverTotalCharge_mu predictedChargeOverTotalCharge_mu predictedChargeOverTotalCharge_mu                                       'F'    [0.244273379445,27.6878967285]
predictedChargeOverTotalCharge_el predictedChargeOverTotalCharge_el predictedChargeOverTotalCharge_el predictedChargeOverTotalCharge_el                                       'F'    [-999.900024414,21.5064907074]
nHits                         nHits                         nHits                         nHits                                                           'F'    [51,8301]
recoE_el/totalQ               recoE_el_D_totalQ             recoE_el/totalQ               recoE_el/totalQ                                                 'F'    [0.0610388442874,29.6625461578]
recoE_mu/totalQ               recoE_mu_D_totalQ             recoE_mu/totalQ               recoE_mu/totalQ                                                 'F'    [0.0610388442874,10.9381780624]
charge2LnL_el/nHits           chargeLikelihoodRatio_el      chargeLikelihoodRatio_el      chargeLikelihoodRatio_el                                        'F'    [0,59.5324745178]
charge2LnL_mu/nHits           chargeLikelihoodRatio_mu      chargeLikelihoodRatio_mu      chargeLikelihoodRatio_mu                                        'F'    [6.21251344681,58.7527008057]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 11 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "deltaCharge2LnL", "deltaTime2LnL", "fracQOutsideRing_mu", "fracPredQOutsideRing_mu", "predictedChargeOverTotalCharge_mu", "predictedChargeOverTotalCharge_el", "nHits", "recoE_el/totalQ", "recoE_mu/totalQ", "charge2LnL_el/nHits", "charge2LnL_mu/nHits" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][11];
   double fMax_1[3][11];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[11];
   double fVmax[11];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[11];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[17][12];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][17];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 12; fWeights[0] = new double[12]; 
   fLayerSize[1] = 17; fWeights[1] = new double[17]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = 0.395642392260164;
   fWeightMatrix0to1[1][0] = 2.16345693588685;
   fWeightMatrix0to1[2][0] = 0.615644726628381;
   fWeightMatrix0to1[3][0] = 2.04824474592762;
   fWeightMatrix0to1[4][0] = -2.26143119270393;
   fWeightMatrix0to1[5][0] = -1.76370244276806;
   fWeightMatrix0to1[6][0] = -0.884648215087015;
   fWeightMatrix0to1[7][0] = 2.31768066624826;
   fWeightMatrix0to1[8][0] = -1.34472114537171;
   fWeightMatrix0to1[9][0] = -0.719502503004355;
   fWeightMatrix0to1[10][0] = -1.77152965182226;
   fWeightMatrix0to1[11][0] = 1.517069656264;
   fWeightMatrix0to1[12][0] = -1.54455610972673;
   fWeightMatrix0to1[13][0] = 0.375444336524833;
   fWeightMatrix0to1[14][0] = -0.687867466056412;
   fWeightMatrix0to1[15][0] = 0.711201915479175;
   fWeightMatrix0to1[0][1] = 0.486629296582123;
   fWeightMatrix0to1[1][1] = 1.71486030891744;
   fWeightMatrix0to1[2][1] = 0.208563540177116;
   fWeightMatrix0to1[3][1] = 1.2736113423535;
   fWeightMatrix0to1[4][1] = -0.797395861702143;
   fWeightMatrix0to1[5][1] = -0.72920339778981;
   fWeightMatrix0to1[6][1] = 0.669714425382686;
   fWeightMatrix0to1[7][1] = -0.525741644732843;
   fWeightMatrix0to1[8][1] = -1.17688378683399;
   fWeightMatrix0to1[9][1] = -0.163544119087379;
   fWeightMatrix0to1[10][1] = 1.40423022590185;
   fWeightMatrix0to1[11][1] = -0.915359652751376;
   fWeightMatrix0to1[12][1] = -1.61206104311899;
   fWeightMatrix0to1[13][1] = -0.0239716058178956;
   fWeightMatrix0to1[14][1] = 0.223889225482051;
   fWeightMatrix0to1[15][1] = 1.62377339675714;
   fWeightMatrix0to1[0][2] = 0.394044382038338;
   fWeightMatrix0to1[1][2] = -0.135900432694597;
   fWeightMatrix0to1[2][2] = 0.307940880061054;
   fWeightMatrix0to1[3][2] = -0.105192710876424;
   fWeightMatrix0to1[4][2] = -1.41709045956754;
   fWeightMatrix0to1[5][2] = 1.86271420859068;
   fWeightMatrix0to1[6][2] = -0.809004990799937;
   fWeightMatrix0to1[7][2] = -0.0732033046960405;
   fWeightMatrix0to1[8][2] = 1.11793851234318;
   fWeightMatrix0to1[9][2] = 0.885124025138814;
   fWeightMatrix0to1[10][2] = 2.06800838405302;
   fWeightMatrix0to1[11][2] = 2.64921465722319;
   fWeightMatrix0to1[12][2] = -0.155839954306887;
   fWeightMatrix0to1[13][2] = -0.71319144092873;
   fWeightMatrix0to1[14][2] = 0.379926311229386;
   fWeightMatrix0to1[15][2] = 0.109006810346711;
   fWeightMatrix0to1[0][3] = 2.87153327925228;
   fWeightMatrix0to1[1][3] = 1.73362898349808;
   fWeightMatrix0to1[2][3] = 1.49600473776985;
   fWeightMatrix0to1[3][3] = 1.90215938106658;
   fWeightMatrix0to1[4][3] = -1.50928801274471;
   fWeightMatrix0to1[5][3] = 1.51341480492733;
   fWeightMatrix0to1[6][3] = -1.72647750708478;
   fWeightMatrix0to1[7][3] = -1.32028535875916;
   fWeightMatrix0to1[8][3] = -1.34673828949475;
   fWeightMatrix0to1[9][3] = -1.8139253566745;
   fWeightMatrix0to1[10][3] = 1.36176275590338;
   fWeightMatrix0to1[11][3] = -0.506012452597037;
   fWeightMatrix0to1[12][3] = -0.971586109787907;
   fWeightMatrix0to1[13][3] = -0.16095264983349;
   fWeightMatrix0to1[14][3] = -1.93599961825167;
   fWeightMatrix0to1[15][3] = 0.780622698333388;
   fWeightMatrix0to1[0][4] = 1.24840811863389;
   fWeightMatrix0to1[1][4] = -0.0864831166014233;
   fWeightMatrix0to1[2][4] = 0.673358928277678;
   fWeightMatrix0to1[3][4] = -1.68383288413138;
   fWeightMatrix0to1[4][4] = 0.575777973477638;
   fWeightMatrix0to1[5][4] = -0.415362766774219;
   fWeightMatrix0to1[6][4] = -0.705371094911315;
   fWeightMatrix0to1[7][4] = -1.16667115810204;
   fWeightMatrix0to1[8][4] = 0.648695285230339;
   fWeightMatrix0to1[9][4] = 0.98275401823341;
   fWeightMatrix0to1[10][4] = 1.10889970372355;
   fWeightMatrix0to1[11][4] = 0.908098809176466;
   fWeightMatrix0to1[12][4] = -1.01180347698226;
   fWeightMatrix0to1[13][4] = -3.38944690091891;
   fWeightMatrix0to1[14][4] = 0.339154224025344;
   fWeightMatrix0to1[15][4] = 0.520496414689153;
   fWeightMatrix0to1[0][5] = 2.40445482605421;
   fWeightMatrix0to1[1][5] = 0.274338611594517;
   fWeightMatrix0to1[2][5] = 0.340161276270957;
   fWeightMatrix0to1[3][5] = -0.490538652939789;
   fWeightMatrix0to1[4][5] = -1.55180654667878;
   fWeightMatrix0to1[5][5] = -0.651062392757406;
   fWeightMatrix0to1[6][5] = 1.22962522471244;
   fWeightMatrix0to1[7][5] = -1.07552882958398;
   fWeightMatrix0to1[8][5] = -1.50144991919893;
   fWeightMatrix0to1[9][5] = -1.54824822619408;
   fWeightMatrix0to1[10][5] = -0.324199937603933;
   fWeightMatrix0to1[11][5] = -0.0868854482396181;
   fWeightMatrix0to1[12][5] = 0.390319711311881;
   fWeightMatrix0to1[13][5] = -1.69288810080728;
   fWeightMatrix0to1[14][5] = -0.504663950467647;
   fWeightMatrix0to1[15][5] = 1.7372167347004;
   fWeightMatrix0to1[0][6] = -0.49220303676398;
   fWeightMatrix0to1[1][6] = -1.78254741542211;
   fWeightMatrix0to1[2][6] = -1.4283361029176;
   fWeightMatrix0to1[3][6] = -0.261738806971044;
   fWeightMatrix0to1[4][6] = -1.22845351065528;
   fWeightMatrix0to1[5][6] = -1.53859892244543;
   fWeightMatrix0to1[6][6] = 0.963764671244602;
   fWeightMatrix0to1[7][6] = 1.8243385047234;
   fWeightMatrix0to1[8][6] = -1.25263082658212;
   fWeightMatrix0to1[9][6] = 1.68891706832729;
   fWeightMatrix0to1[10][6] = -0.630956912972757;
   fWeightMatrix0to1[11][6] = -2.43527353337615;
   fWeightMatrix0to1[12][6] = 0.187129947094177;
   fWeightMatrix0to1[13][6] = 0.7479812700754;
   fWeightMatrix0to1[14][6] = -2.60507332893455;
   fWeightMatrix0to1[15][6] = 0.305213152100217;
   fWeightMatrix0to1[0][7] = 1.15225488209929;
   fWeightMatrix0to1[1][7] = 0.271236358719776;
   fWeightMatrix0to1[2][7] = -1.56473170622555;
   fWeightMatrix0to1[3][7] = 2.00195237657872;
   fWeightMatrix0to1[4][7] = -0.222834046849821;
   fWeightMatrix0to1[5][7] = -0.560744084244685;
   fWeightMatrix0to1[6][7] = 0.951315916393653;
   fWeightMatrix0to1[7][7] = -1.25027366241199;
   fWeightMatrix0to1[8][7] = -1.73225869290338;
   fWeightMatrix0to1[9][7] = 0.142567127176034;
   fWeightMatrix0to1[10][7] = -0.308542014499491;
   fWeightMatrix0to1[11][7] = -0.309572260141218;
   fWeightMatrix0to1[12][7] = 1.78449091857382;
   fWeightMatrix0to1[13][7] = 0.554641465682832;
   fWeightMatrix0to1[14][7] = -0.60522431435445;
   fWeightMatrix0to1[15][7] = 0.202282456522319;
   fWeightMatrix0to1[0][8] = -0.644639903496717;
   fWeightMatrix0to1[1][8] = 0.797532841000156;
   fWeightMatrix0to1[2][8] = -0.157134204726829;
   fWeightMatrix0to1[3][8] = -1.12615603344415;
   fWeightMatrix0to1[4][8] = 0.391177685503264;
   fWeightMatrix0to1[5][8] = -1.17223649786289;
   fWeightMatrix0to1[6][8] = 0.0828549604579415;
   fWeightMatrix0to1[7][8] = 1.14647506120735;
   fWeightMatrix0to1[8][8] = 1.69647338211277;
   fWeightMatrix0to1[9][8] = -1.955234378938;
   fWeightMatrix0to1[10][8] = 0.0486305010768163;
   fWeightMatrix0to1[11][8] = -0.276842822736724;
   fWeightMatrix0to1[12][8] = 2.22673330690653;
   fWeightMatrix0to1[13][8] = 1.53142877337052;
   fWeightMatrix0to1[14][8] = -1.06799727628438;
   fWeightMatrix0to1[15][8] = -0.155250868779272;
   fWeightMatrix0to1[0][9] = -1.72940079254381;
   fWeightMatrix0to1[1][9] = 1.55774965866952;
   fWeightMatrix0to1[2][9] = 1.58108732121428;
   fWeightMatrix0to1[3][9] = -0.900340256345108;
   fWeightMatrix0to1[4][9] = -0.645799432899593;
   fWeightMatrix0to1[5][9] = 0.463732784718112;
   fWeightMatrix0to1[6][9] = -1.41327156345341;
   fWeightMatrix0to1[7][9] = 0.568549178870882;
   fWeightMatrix0to1[8][9] = 1.61477220343534;
   fWeightMatrix0to1[9][9] = -0.67387577862464;
   fWeightMatrix0to1[10][9] = -0.773217569815882;
   fWeightMatrix0to1[11][9] = 1.84724629871929;
   fWeightMatrix0to1[12][9] = 1.47486270090883;
   fWeightMatrix0to1[13][9] = -1.1240548180056;
   fWeightMatrix0to1[14][9] = 1.02125868320797;
   fWeightMatrix0to1[15][9] = -1.39511515607593;
   fWeightMatrix0to1[0][10] = 1.39786571022992;
   fWeightMatrix0to1[1][10] = 0.665584507021733;
   fWeightMatrix0to1[2][10] = 0.881041161873324;
   fWeightMatrix0to1[3][10] = 0.320097125062227;
   fWeightMatrix0to1[4][10] = 0.829108502106607;
   fWeightMatrix0to1[5][10] = -0.175305195916363;
   fWeightMatrix0to1[6][10] = -0.779614067104167;
   fWeightMatrix0to1[7][10] = 0.910184914696762;
   fWeightMatrix0to1[8][10] = -1.01487434974973;
   fWeightMatrix0to1[9][10] = -0.770815117774317;
   fWeightMatrix0to1[10][10] = 1.37482218264398;
   fWeightMatrix0to1[11][10] = 2.00639276329532;
   fWeightMatrix0to1[12][10] = 0.413268293139105;
   fWeightMatrix0to1[13][10] = 0.856805700468651;
   fWeightMatrix0to1[14][10] = 2.21317553980213;
   fWeightMatrix0to1[15][10] = -1.89524786710463;
   fWeightMatrix0to1[0][11] = 0.641730154289665;
   fWeightMatrix0to1[1][11] = -0.0695449415040683;
   fWeightMatrix0to1[2][11] = 0.285857572623251;
   fWeightMatrix0to1[3][11] = -1.36683501241046;
   fWeightMatrix0to1[4][11] = -1.64190889046983;
   fWeightMatrix0to1[5][11] = 0.754917182706995;
   fWeightMatrix0to1[6][11] = 1.60448704776793;
   fWeightMatrix0to1[7][11] = -1.77169977630208;
   fWeightMatrix0to1[8][11] = -0.041243184815347;
   fWeightMatrix0to1[9][11] = -0.45327734717062;
   fWeightMatrix0to1[10][11] = 0.172318924197829;
   fWeightMatrix0to1[11][11] = 2.68348020410472;
   fWeightMatrix0to1[12][11] = -1.65152632189694;
   fWeightMatrix0to1[13][11] = -0.385460006385427;
   fWeightMatrix0to1[14][11] = -1.02723217219025;
   fWeightMatrix0to1[15][11] = 1.02543987199955;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.494740771960094;
   fWeightMatrix1to2[0][1] = -0.183269221708405;
   fWeightMatrix1to2[0][2] = -0.288198327354536;
   fWeightMatrix1to2[0][3] = 0.51516801023094;
   fWeightMatrix1to2[0][4] = -1.03207361046189;
   fWeightMatrix1to2[0][5] = -0.0613155148479171;
   fWeightMatrix1to2[0][6] = 0.12691783684497;
   fWeightMatrix1to2[0][7] = -0.769880288819801;
   fWeightMatrix1to2[0][8] = -0.0246327027532011;
   fWeightMatrix1to2[0][9] = 0.0610913451114756;
   fWeightMatrix1to2[0][10] = 0.158255088188499;
   fWeightMatrix1to2[0][11] = -0.551927878486096;
   fWeightMatrix1to2[0][12] = 0.932081115562335;
   fWeightMatrix1to2[0][13] = 0.96019537265716;
   fWeightMatrix1to2[0][14] = 0.62858263307509;
   fWeightMatrix1to2[0][15] = -0.538128068844415;
   fWeightMatrix1to2[0][16] = 1.16456130414438;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // clean up the arrays
   for (int lIdx = 0; lIdx < 3; lIdx++) {
      delete[] fWeights[lIdx];
   }
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -16716.9316406;
   fMax_1[0][0] = 1407.20666504;
   fMin_1[1][0] = -12000.4570312;
   fMax_1[1][0] = 1986.66943359;
   fMin_1[2][0] = -16716.9316406;
   fMax_1[2][0] = 1986.66943359;
   fMin_1[0][1] = -8358.29003906;
   fMax_1[0][1] = 7772.99316406;
   fMin_1[1][1] = -10892.2509766;
   fMax_1[1][1] = 5917.52050781;
   fMin_1[2][1] = -10892.2509766;
   fMax_1[2][1] = 7772.99316406;
   fMin_1[0][2] = 0.0325821451843;
   fMax_1[0][2] = 1;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = 0.0887037888169;
   fMax_1[0][3] = 0.979899227619;
   fMin_1[1][3] = 0.0803388804197;
   fMax_1[1][3] = 1;
   fMin_1[2][3] = 0.0803388804197;
   fMax_1[2][3] = 1;
   fMin_1[0][4] = 0.244273379445;
   fMax_1[0][4] = 14.9202194214;
   fMin_1[1][4] = 0.28193795681;
   fMax_1[1][4] = 27.6878967285;
   fMin_1[2][4] = 0.244273379445;
   fMax_1[2][4] = 27.6878967285;
   fMin_1[0][5] = -999.900024414;
   fMax_1[0][5] = 7.81826734543;
   fMin_1[1][5] = -999.900024414;
   fMax_1[1][5] = 21.5064907074;
   fMin_1[2][5] = -999.900024414;
   fMax_1[2][5] = 21.5064907074;
   fMin_1[0][6] = 83;
   fMax_1[0][6] = 8301;
   fMin_1[1][6] = 51;
   fMax_1[1][6] = 7347;
   fMin_1[2][6] = 51;
   fMax_1[2][6] = 8301;
   fMin_1[0][7] = 0.110606491566;
   fMax_1[0][7] = 29.6625461578;
   fMin_1[1][7] = 0.0610388442874;
   fMax_1[1][7] = 14.8830461502;
   fMin_1[2][7] = 0.0610388442874;
   fMax_1[2][7] = 29.6625461578;
   fMin_1[0][8] = 0.101162150502;
   fMax_1[0][8] = 5.56668233871;
   fMin_1[1][8] = 0.0610388442874;
   fMax_1[1][8] = 10.9381780624;
   fMin_1[2][8] = 0.0610388442874;
   fMax_1[2][8] = 10.9381780624;
   fMin_1[0][9] = 0;
   fMax_1[0][9] = 25.2747039795;
   fMin_1[1][9] = 0;
   fMax_1[1][9] = 59.5324745178;
   fMin_1[2][9] = 0;
   fMax_1[2][9] = 59.5324745178;
   fMin_1[0][10] = 6.21251344681;
   fMax_1[0][10] = 36.6185951233;
   fMin_1[1][10] = 6.31372499466;
   fMax_1[1][10] = 58.7527008057;
   fMin_1[2][10] = 6.21251344681;
   fMax_1[2][10] = 58.7527008057;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 11;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   static std::vector<int> indicesGet;
   static std::vector<int> indicesPut;

   if ( indicesGet.empty() ) { 
      indicesGet.reserve(fNvars);
      indicesGet.push_back( 0);
      indicesGet.push_back( 1);
      indicesGet.push_back( 2);
      indicesGet.push_back( 3);
      indicesGet.push_back( 4);
      indicesGet.push_back( 5);
      indicesGet.push_back( 6);
      indicesGet.push_back( 7);
      indicesGet.push_back( 8);
      indicesGet.push_back( 9);
      indicesGet.push_back( 10);
   } 
   if ( indicesPut.empty() ) { 
      indicesPut.reserve(fNvars);
      indicesPut.push_back( 0);
      indicesPut.push_back( 1);
      indicesPut.push_back( 2);
      indicesPut.push_back( 3);
      indicesPut.push_back( 4);
      indicesPut.push_back( 5);
      indicesPut.push_back( 6);
      indicesPut.push_back( 7);
      indicesPut.push_back( 8);
      indicesPut.push_back( 9);
      indicesPut.push_back( 10);
   } 

   static std::vector<double> dv;
   dv.resize(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<11;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
