#!/bin/sh

NUMTHROWS=100000000
NUMBINS=1000
BINSPERJOB=10
MIN=0
MAX=10
DIR=$WCSIMANAHOME/macros/GenerateDigitizerPDFs/

for (( MUBIN=0; MUBIN<$NUMBINS; MUBIN=MUBIN+BINSPERJOB ))
do
	qsub -q short -v DIR=$DIR,MUBIN=$MUBIN,NUMTHROWS=$NUMTHROWS,NUMBINS=$NUMBINS,MIN=$MIN,MAX=$MAX,BINSPERJOB=$BINSPERJOB RunDigitizerPDFMaker.sh
done
