#!/bin/sh

NUMTHROWS=10000000
NUMBINS=1000
BINSPERJOB=20
MIN=0
MAX=20
DIR=$WCSIMANAHOME/macros/GenerateDigitizerPDFs/
TYPE=0

for (( MUBIN=0; MUBIN<$NUMBINS; MUBIN=MUBIN+BINSPERJOB ))
do
	qsub -q short -v DIR=$DIR,MUBIN=$MUBIN,TYPE=$TYPE,NUMTHROWS=$NUMTHROWS,NUMBINS=$NUMBINS,MIN=$MIN,MAX=$MAX,BINSPERJOB=$BINSPERJOB RunDigitizerPDFMaker.sh
done
