// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.30/00       [335360]
Creator        : jtingey
Date           : Wed Mar  7 15:42:00 2018
Host           : Linux pc143.hep.ucl.ac.uk 2.6.18-308.11.1.el5 #1 SMP Tue Jul 10 15:47:47 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /unix/chips/jtingey/CHIPS/code/WCSimAnalysis/pid/cosmicPid
Training events: 3945
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 16
fVtxZ                         fVtxZ                         fVtxZ                         fVtxZ                                                           'F'    [-950,950]
fvtxR                         fvtxR                         fvtxR                         fvtxR                                                           'F'    [13.6949520111,1246.93212891]
fDirX                         fDirX                         fDirX                         fDirX                                                           'F'    [-0.99983215332,0.999989211559]
fDirY                         fDirY                         fDirY                         fDirY                                                           'F'    [-0.997001230717,0.995773375034]
fDirZ                         fDirZ                         fDirZ                         fDirZ                                                           'F'    [-0.999999940395,0.985570847988]
fFracHitsDownstream           fFracHitsDownstream           fFracHitsDownstream           fFracHitsDownstream                                             'F'    [0,1]
fFracHitsUpstream             fFracHitsUpstream             fFracHitsUpstream             fFracHitsUpstream                                               'F'    [0,1]
fNHits                        fNHits                        fNHits                        fNHits                                                          'F'    [50,1910]
fEnergy                       fEnergy                       fEnergy                       fEnergy                                                         'F'    [500,5000]
fPredictedOverTotalCharge     fPredictedOverTotalCharge     fPredictedOverTotalCharge     fPredictedOverTotalCharge                                       'F'    [0.0041483649984,6.77362728119]
fFracTotalQInRing             fFracTotalQInRing             fFracTotalQInRing             fFracTotalQInRing                                               'F'    [0,0.995039105415]
fFracTotalQOutsideRing        fFracTotalQOutsideRing        fFracTotalQOutsideRing        fFracTotalQOutsideRing                                          'F'    [0,1]
fFracTotalQInRingHole         fFracTotalQInRingHole         fFracTotalQInRingHole         fFracTotalQInRingHole                                           'F'    [0,1]
fFracNHitsInRing              fFracNHitsInRing              fFracNHitsInRing              fFracNHitsInRing                                                'F'    [0,0.985714256763]
fFracNHitsOutsideRing         fFracNHitsOutsideRing         fFracNHitsOutsideRing         fFracNHitsOutsideRing                                           'F'    [0,1]
fFracNHitsInRingHole          fFracNHitsInRingHole          fFracNHitsInRingHole          fFracNHitsInRingHole                                            'F'    [0,1]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 16 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "fVtxZ", "fvtxR", "fDirX", "fDirY", "fDirZ", "fFracHitsDownstream", "fFracHitsUpstream", "fNHits", "fEnergy", "fPredictedOverTotalCharge", "fFracTotalQInRing", "fFracTotalQOutsideRing", "fFracTotalQInRingHole", "fFracNHitsInRing", "fFracNHitsOutsideRing", "fFracNHitsInRingHole" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 0.99999988079071;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 0.99999988079071;
      fVmin[4] = -1;
      fVmax[4] = 0.99999988079071;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 1;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 0.99999988079071;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 0.99999988079071;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][16];
   double fMax_1[3][16];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[16];
   double fVmax[16];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[16];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[22][17];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][22];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 17; fWeights[0] = new double[17]; 
   fLayerSize[1] = 22; fWeights[1] = new double[22]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.466269352892009;
   fWeightMatrix0to1[1][0] = 2.13126475108547;
   fWeightMatrix0to1[2][0] = 0.834196261504629;
   fWeightMatrix0to1[3][0] = 1.68565719916765;
   fWeightMatrix0to1[4][0] = -1.30472447286616;
   fWeightMatrix0to1[5][0] = -0.944738030900966;
   fWeightMatrix0to1[6][0] = -0.334948022771058;
   fWeightMatrix0to1[7][0] = 1.93089370043887;
   fWeightMatrix0to1[8][0] = -0.768463555947855;
   fWeightMatrix0to1[9][0] = -0.849573830169729;
   fWeightMatrix0to1[10][0] = -1.59134435911718;
   fWeightMatrix0to1[11][0] = -0.386535956768744;
   fWeightMatrix0to1[12][0] = -1.19907110659567;
   fWeightMatrix0to1[13][0] = -0.594063050373759;
   fWeightMatrix0to1[14][0] = -0.781311360904379;
   fWeightMatrix0to1[15][0] = 0.234184633240588;
   fWeightMatrix0to1[16][0] = -0.645829216444324;
   fWeightMatrix0to1[17][0] = 1.74601179255765;
   fWeightMatrix0to1[18][0] = 0.152272568911263;
   fWeightMatrix0to1[19][0] = 1.35169038040548;
   fWeightMatrix0to1[20][0] = -0.242552335287447;
   fWeightMatrix0to1[0][1] = -0.749046674069999;
   fWeightMatrix0to1[1][1] = 0.764816755561329;
   fWeightMatrix0to1[2][1] = 0.713072964029682;
   fWeightMatrix0to1[3][1] = -1.12060239194065;
   fWeightMatrix0to1[4][1] = -0.0144348655301127;
   fWeightMatrix0to1[5][1] = 1.4270209300707;
   fWeightMatrix0to1[6][1] = -0.913111482478384;
   fWeightMatrix0to1[7][1] = -1.60160563929898;
   fWeightMatrix0to1[8][1] = 0.206721756186111;
   fWeightMatrix0to1[9][1] = -0.191518782391858;
   fWeightMatrix0to1[10][1] = 1.60955179524683;
   fWeightMatrix0to1[11][1] = -0.294193427171405;
   fWeightMatrix0to1[12][1] = -0.0374993999381146;
   fWeightMatrix0to1[13][1] = 0.17844736104093;
   fWeightMatrix0to1[14][1] = 0.125689398078963;
   fWeightMatrix0to1[15][1] = 0.423602879758813;
   fWeightMatrix0to1[16][1] = 1.58212752922393;
   fWeightMatrix0to1[17][1] = -1.08891686266791;
   fWeightMatrix0to1[18][1] = 0.828247296910681;
   fWeightMatrix0to1[19][1] = 1.15797709025597;
   fWeightMatrix0to1[20][1] = 0.684762260981943;
   fWeightMatrix0to1[0][2] = 2.75437066494766;
   fWeightMatrix0to1[1][2] = 1.02741133573968;
   fWeightMatrix0to1[2][2] = -1.11667935777222;
   fWeightMatrix0to1[3][2] = -1.77661378675868;
   fWeightMatrix0to1[4][2] = 1.2207732298581;
   fWeightMatrix0to1[5][2] = 0.139180606654692;
   fWeightMatrix0to1[6][2] = 1.14349062144721;
   fWeightMatrix0to1[7][2] = 1.33723440922895;
   fWeightMatrix0to1[8][2] = 1.56347778723057;
   fWeightMatrix0to1[9][2] = 1.09504758554086;
   fWeightMatrix0to1[10][2] = -1.59831157364261;
   fWeightMatrix0to1[11][2] = 1.4167354617064;
   fWeightMatrix0to1[12][2] = -1.72851177681918;
   fWeightMatrix0to1[13][2] = -0.684258377225914;
   fWeightMatrix0to1[14][2] = -1.53020209029051;
   fWeightMatrix0to1[15][2] = -3.35759381930617;
   fWeightMatrix0to1[16][2] = 1.48567468502257;
   fWeightMatrix0to1[17][2] = 0.480011227154713;
   fWeightMatrix0to1[18][2] = -1.82444529071864;
   fWeightMatrix0to1[19][2] = 0.372045216632278;
   fWeightMatrix0to1[20][2] = -0.306664982906712;
   fWeightMatrix0to1[0][3] = -0.185680838363598;
   fWeightMatrix0to1[1][3] = 1.7709461371152;
   fWeightMatrix0to1[2][3] = -0.412865822803582;
   fWeightMatrix0to1[3][3] = 0.0235846892353003;
   fWeightMatrix0to1[4][3] = -1.16700999131884;
   fWeightMatrix0to1[5][3] = 0.728153507858019;
   fWeightMatrix0to1[6][3] = -1.11129464389308;
   fWeightMatrix0to1[7][3] = -0.640739191871489;
   fWeightMatrix0to1[8][3] = -1.25526029409427;
   fWeightMatrix0to1[9][3] = 0.981562002706617;
   fWeightMatrix0to1[10][3] = 1.11498032377479;
   fWeightMatrix0to1[11][3] = 1.36696698331127;
   fWeightMatrix0to1[12][3] = -0.37971742527773;
   fWeightMatrix0to1[13][3] = -1.22473017784009;
   fWeightMatrix0to1[14][3] = -1.94016169262851;
   fWeightMatrix0to1[15][3] = 0.19166555138239;
   fWeightMatrix0to1[16][3] = 0.318437512358629;
   fWeightMatrix0to1[17][3] = 1.73051420125397;
   fWeightMatrix0to1[18][3] = 0.521987036369696;
   fWeightMatrix0to1[19][3] = 0.975837307952231;
   fWeightMatrix0to1[20][3] = -0.399369638247396;
   fWeightMatrix0to1[0][4] = 2.93302952645134;
   fWeightMatrix0to1[1][4] = -0.325609896153566;
   fWeightMatrix0to1[2][4] = 0.108340964089678;
   fWeightMatrix0to1[3][4] = -1.07709282006989;
   fWeightMatrix0to1[4][4] = -1.98762993659059;
   fWeightMatrix0to1[5][4] = -1.84634719037154;
   fWeightMatrix0to1[6][4] = -0.34632233703155;
   fWeightMatrix0to1[7][4] = -0.244052390305351;
   fWeightMatrix0to1[8][4] = 1.26936189512565;
   fWeightMatrix0to1[9][4] = -1.57430627860241;
   fWeightMatrix0to1[10][4] = -0.843591534021539;
   fWeightMatrix0to1[11][4] = 1.55745257678315;
   fWeightMatrix0to1[12][4] = -1.17129819517942;
   fWeightMatrix0to1[13][4] = -1.44744713218258;
   fWeightMatrix0to1[14][4] = -1.80016210441995;
   fWeightMatrix0to1[15][4] = -2.76907488751944;
   fWeightMatrix0to1[16][4] = -1.75794749793418;
   fWeightMatrix0to1[17][4] = -1.92989692792747;
   fWeightMatrix0to1[18][4] = 0.668119088283215;
   fWeightMatrix0to1[19][4] = 1.62841120030766;
   fWeightMatrix0to1[20][4] = -1.02018215437367;
   fWeightMatrix0to1[0][5] = 0.845568616413075;
   fWeightMatrix0to1[1][5] = -1.11390481458725;
   fWeightMatrix0to1[2][5] = -0.775472157927949;
   fWeightMatrix0to1[3][5] = -0.253998656289602;
   fWeightMatrix0to1[4][5] = 0.904807128567404;
   fWeightMatrix0to1[5][5] = -1.30983695740627;
   fWeightMatrix0to1[6][5] = 0.396797153236083;
   fWeightMatrix0to1[7][5] = 0.0932156097305864;
   fWeightMatrix0to1[8][5] = 0.713913003403421;
   fWeightMatrix0to1[9][5] = -1.18185935365451;
   fWeightMatrix0to1[10][5] = 1.88415997461042;
   fWeightMatrix0to1[11][5] = 0.40303510277831;
   fWeightMatrix0to1[12][5] = -0.531008133470741;
   fWeightMatrix0to1[13][5] = 0.146960100412429;
   fWeightMatrix0to1[14][5] = -0.898575763728137;
   fWeightMatrix0to1[15][5] = -1.49568945763701;
   fWeightMatrix0to1[16][5] = 0.0428874374371748;
   fWeightMatrix0to1[17][5] = -0.419423229110606;
   fWeightMatrix0to1[18][5] = 1.65455100999902;
   fWeightMatrix0to1[19][5] = 0.750182821902251;
   fWeightMatrix0to1[20][5] = 0.0639856468490125;
   fWeightMatrix0to1[0][6] = 0.452942070972278;
   fWeightMatrix0to1[1][6] = 0.338493483149699;
   fWeightMatrix0to1[2][6] = -1.82899356671024;
   fWeightMatrix0to1[3][6] = 1.28223172581622;
   fWeightMatrix0to1[4][6] = -0.423665003589857;
   fWeightMatrix0to1[5][6] = -2.29532996818724;
   fWeightMatrix0to1[6][6] = 0.522029591060414;
   fWeightMatrix0to1[7][6] = -1.23688069941501;
   fWeightMatrix0to1[8][6] = -0.198603296944136;
   fWeightMatrix0to1[9][6] = 0.938387948716709;
   fWeightMatrix0to1[10][6] = 1.72036169629894;
   fWeightMatrix0to1[11][6] = -1.92660751091666;
   fWeightMatrix0to1[12][6] = -0.0788557834289963;
   fWeightMatrix0to1[13][6] = 2.18457526452237;
   fWeightMatrix0to1[14][6] = 1.43624509026285;
   fWeightMatrix0to1[15][6] = 0.0681798616711202;
   fWeightMatrix0to1[16][6] = -1.35919465116017;
   fWeightMatrix0to1[17][6] = -0.132432094289724;
   fWeightMatrix0to1[18][6] = -1.29769311382324;
   fWeightMatrix0to1[19][6] = 1.59596128421437;
   fWeightMatrix0to1[20][6] = 1.13781788843735;
   fWeightMatrix0to1[0][7] = -1.25701726263418;
   fWeightMatrix0to1[1][7] = -0.288449634729955;
   fWeightMatrix0to1[2][7] = 0.0908375390587425;
   fWeightMatrix0to1[3][7] = -1.32499527518543;
   fWeightMatrix0to1[4][7] = 0.2951983147247;
   fWeightMatrix0to1[5][7] = 1.69622896255047;
   fWeightMatrix0to1[6][7] = -0.804220826571159;
   fWeightMatrix0to1[7][7] = -0.804707412689357;
   fWeightMatrix0to1[8][7] = 0.565445480920748;
   fWeightMatrix0to1[9][7] = 1.30643500924465;
   fWeightMatrix0to1[10][7] = 0.621358074722935;
   fWeightMatrix0to1[11][7] = 0.948916032222921;
   fWeightMatrix0to1[12][7] = -1.42313953513237;
   fWeightMatrix0to1[13][7] = 1.1362704196111;
   fWeightMatrix0to1[14][7] = 0.510847508908638;
   fWeightMatrix0to1[15][7] = 1.02911871112376;
   fWeightMatrix0to1[16][7] = 0.526179707585494;
   fWeightMatrix0to1[17][7] = 0.773095437154053;
   fWeightMatrix0to1[18][7] = -0.480577785051427;
   fWeightMatrix0to1[19][7] = -0.573158377459671;
   fWeightMatrix0to1[20][7] = 1.24034523231182;
   fWeightMatrix0to1[0][8] = -0.73693817880505;
   fWeightMatrix0to1[1][8] = -0.550135531121995;
   fWeightMatrix0to1[2][8] = 1.617577064879;
   fWeightMatrix0to1[3][8] = 0.998266817660659;
   fWeightMatrix0to1[4][8] = -0.770350599977669;
   fWeightMatrix0to1[5][8] = 1.44150603191397;
   fWeightMatrix0to1[6][8] = 1.46851970791437;
   fWeightMatrix0to1[7][8] = -1.9114211939263;
   fWeightMatrix0to1[8][8] = 0.944698755716928;
   fWeightMatrix0to1[9][8] = 0.076777912489707;
   fWeightMatrix0to1[10][8] = 0.541492152769481;
   fWeightMatrix0to1[11][8] = -1.429562702143;
   fWeightMatrix0to1[12][8] = -1.71397063748675;
   fWeightMatrix0to1[13][8] = 0.815366131991062;
   fWeightMatrix0to1[14][8] = 1.39608917953748;
   fWeightMatrix0to1[15][8] = 0.120323301986881;
   fWeightMatrix0to1[16][8] = -0.169288064636038;
   fWeightMatrix0to1[17][8] = -0.763137894561473;
   fWeightMatrix0to1[18][8] = 0.585782790538573;
   fWeightMatrix0to1[19][8] = 1.79284144900986;
   fWeightMatrix0to1[20][8] = -0.102714848285429;
   fWeightMatrix0to1[0][9] = 0.194297692333819;
   fWeightMatrix0to1[1][9] = -0.895126480716763;
   fWeightMatrix0to1[2][9] = 0.961031485873724;
   fWeightMatrix0to1[3][9] = 1.51682311024788;
   fWeightMatrix0to1[4][9] = 0.697714461369738;
   fWeightMatrix0to1[5][9] = 0.316141745761293;
   fWeightMatrix0to1[6][9] = -1.07922777949562;
   fWeightMatrix0to1[7][9] = -2.29438307540849;
   fWeightMatrix0to1[8][9] = 1.21366762662978;
   fWeightMatrix0to1[9][9] = 0.683085160251746;
   fWeightMatrix0to1[10][9] = -1.33977890951226;
   fWeightMatrix0to1[11][9] = -0.747995263535759;
   fWeightMatrix0to1[12][9] = 0.417236377467397;
   fWeightMatrix0to1[13][9] = -0.397574188981729;
   fWeightMatrix0to1[14][9] = -2.19682611240694;
   fWeightMatrix0to1[15][9] = 0.951419063725296;
   fWeightMatrix0to1[16][9] = 0.623215551002684;
   fWeightMatrix0to1[17][9] = -0.636178781335119;
   fWeightMatrix0to1[18][9] = -0.158822170168538;
   fWeightMatrix0to1[19][9] = 1.66802108285724;
   fWeightMatrix0to1[20][9] = 1.15660962035925;
   fWeightMatrix0to1[0][10] = 0.253017928443744;
   fWeightMatrix0to1[1][10] = -0.210419508913693;
   fWeightMatrix0to1[2][10] = -1.78784255072051;
   fWeightMatrix0to1[3][10] = -0.928133428306106;
   fWeightMatrix0to1[4][10] = 1.57784886615997;
   fWeightMatrix0to1[5][10] = 1.25100017184714;
   fWeightMatrix0to1[6][10] = 0.587294013262997;
   fWeightMatrix0to1[7][10] = 0.226999070549416;
   fWeightMatrix0to1[8][10] = 2.04661907730663;
   fWeightMatrix0to1[9][10] = -1.92595683771815;
   fWeightMatrix0to1[10][10] = -1.33028603402463;
   fWeightMatrix0to1[11][10] = 0.12272283169303;
   fWeightMatrix0to1[12][10] = -1.48135687945586;
   fWeightMatrix0to1[13][10] = 0.839912082263148;
   fWeightMatrix0to1[14][10] = 1.36591637140001;
   fWeightMatrix0to1[15][10] = -0.683860995265274;
   fWeightMatrix0to1[16][10] = 0.824596623262905;
   fWeightMatrix0to1[17][10] = -0.144445855571426;
   fWeightMatrix0to1[18][10] = -1.50647692976923;
   fWeightMatrix0to1[19][10] = -1.05619497828218;
   fWeightMatrix0to1[20][10] = 1.08729762924457;
   fWeightMatrix0to1[0][11] = 0.668194858391553;
   fWeightMatrix0to1[1][11] = 1.29239956805885;
   fWeightMatrix0to1[2][11] = -1.04790402193761;
   fWeightMatrix0to1[3][11] = 1.62449561397549;
   fWeightMatrix0to1[4][11] = -1.86276220058241;
   fWeightMatrix0to1[5][11] = 1.03878958699573;
   fWeightMatrix0to1[6][11] = -0.117138016942689;
   fWeightMatrix0to1[7][11] = -1.67148172625794;
   fWeightMatrix0to1[8][11] = -1.02683335770451;
   fWeightMatrix0to1[9][11] = -1.39939871800144;
   fWeightMatrix0to1[10][11] = -0.335807768565043;
   fWeightMatrix0to1[11][11] = -2.068758437128;
   fWeightMatrix0to1[12][11] = -1.28782334290935;
   fWeightMatrix0to1[13][11] = -2.1453727218605;
   fWeightMatrix0to1[14][11] = 0.0875005251794363;
   fWeightMatrix0to1[15][11] = -0.681419572393986;
   fWeightMatrix0to1[16][11] = -1.79743341283002;
   fWeightMatrix0to1[17][11] = 1.33480768454109;
   fWeightMatrix0to1[18][11] = -1.08733118103123;
   fWeightMatrix0to1[19][11] = 0.178248258017133;
   fWeightMatrix0to1[20][11] = -0.930697574556508;
   fWeightMatrix0to1[0][12] = 0.453802715942983;
   fWeightMatrix0to1[1][12] = 1.84023625437558;
   fWeightMatrix0to1[2][12] = 0.985766155516285;
   fWeightMatrix0to1[3][12] = -0.910554006540775;
   fWeightMatrix0to1[4][12] = -1.72237785397293;
   fWeightMatrix0to1[5][12] = -1.16142536880192;
   fWeightMatrix0to1[6][12] = -0.913012006001969;
   fWeightMatrix0to1[7][12] = -1.82713520994346;
   fWeightMatrix0to1[8][12] = 0.132744264008909;
   fWeightMatrix0to1[9][12] = 0.276436579906592;
   fWeightMatrix0to1[10][12] = 1.87744618522503;
   fWeightMatrix0to1[11][12] = -0.443399449153021;
   fWeightMatrix0to1[12][12] = 0.0929021798876897;
   fWeightMatrix0to1[13][12] = -0.698987740264362;
   fWeightMatrix0to1[14][12] = -1.84317901552121;
   fWeightMatrix0to1[15][12] = 0.0545698212639394;
   fWeightMatrix0to1[16][12] = 1.16253829325546;
   fWeightMatrix0to1[17][12] = -0.828409888801587;
   fWeightMatrix0to1[18][12] = -1.08468691921072;
   fWeightMatrix0to1[19][12] = 0.860082963986838;
   fWeightMatrix0to1[20][12] = 1.14181761471835;
   fWeightMatrix0to1[0][13] = 0.668016874478326;
   fWeightMatrix0to1[1][13] = -0.593094468909047;
   fWeightMatrix0to1[2][13] = -0.298913034927588;
   fWeightMatrix0to1[3][13] = 1.44712044237895;
   fWeightMatrix0to1[4][13] = 0.789050501933053;
   fWeightMatrix0to1[5][13] = 0.856168469652735;
   fWeightMatrix0to1[6][13] = -0.502384270649849;
   fWeightMatrix0to1[7][13] = 0.229182550798039;
   fWeightMatrix0to1[8][13] = -0.329745035389236;
   fWeightMatrix0to1[9][13] = -1.70933953702156;
   fWeightMatrix0to1[10][13] = -0.552293355811733;
   fWeightMatrix0to1[11][13] = -1.53642519968452;
   fWeightMatrix0to1[12][13] = -1.56143350317739;
   fWeightMatrix0to1[13][13] = -1.70074189264056;
   fWeightMatrix0to1[14][13] = 1.23098647986134;
   fWeightMatrix0to1[15][13] = -1.75545684809774;
   fWeightMatrix0to1[16][13] = 1.72869329459582;
   fWeightMatrix0to1[17][13] = -1.61788328024849;
   fWeightMatrix0to1[18][13] = 1.3178333681071;
   fWeightMatrix0to1[19][13] = -1.08308207875583;
   fWeightMatrix0to1[20][13] = 0.485528177228541;
   fWeightMatrix0to1[0][14] = 0.558370781700127;
   fWeightMatrix0to1[1][14] = -1.55310320360076;
   fWeightMatrix0to1[2][14] = 0.371491130057831;
   fWeightMatrix0to1[3][14] = 0.569867135636678;
   fWeightMatrix0to1[4][14] = -1.89696380107559;
   fWeightMatrix0to1[5][14] = -1.19482913994867;
   fWeightMatrix0to1[6][14] = -1.76756368147454;
   fWeightMatrix0to1[7][14] = -0.981428628513429;
   fWeightMatrix0to1[8][14] = 2.13384529270181;
   fWeightMatrix0to1[9][14] = -0.124004984774345;
   fWeightMatrix0to1[10][14] = 0.333864140981702;
   fWeightMatrix0to1[11][14] = -1.06197626101099;
   fWeightMatrix0to1[12][14] = -0.8563763028362;
   fWeightMatrix0to1[13][14] = -1.96069833747979;
   fWeightMatrix0to1[14][14] = -0.856114994375149;
   fWeightMatrix0to1[15][14] = -0.761304309803513;
   fWeightMatrix0to1[16][14] = 0.737490228229192;
   fWeightMatrix0to1[17][14] = -1.35508658587914;
   fWeightMatrix0to1[18][14] = -1.48022445997326;
   fWeightMatrix0to1[19][14] = 1.78008726013413;
   fWeightMatrix0to1[20][14] = 0.480820925583047;
   fWeightMatrix0to1[0][15] = 0.197490975976801;
   fWeightMatrix0to1[1][15] = 1.88495530488201;
   fWeightMatrix0to1[2][15] = -2.04140204295892;
   fWeightMatrix0to1[3][15] = 1.34703583526378;
   fWeightMatrix0to1[4][15] = 0.711994000183301;
   fWeightMatrix0to1[5][15] = -1.17509311659058;
   fWeightMatrix0to1[6][15] = -0.933259208742768;
   fWeightMatrix0to1[7][15] = -0.207361390661343;
   fWeightMatrix0to1[8][15] = -1.27507313897918;
   fWeightMatrix0to1[9][15] = 0.607669623059977;
   fWeightMatrix0to1[10][15] = 1.92338057738803;
   fWeightMatrix0to1[11][15] = 1.19926930885748;
   fWeightMatrix0to1[12][15] = 1.51471627548107;
   fWeightMatrix0to1[13][15] = -1.4870163725011;
   fWeightMatrix0to1[14][15] = 1.18320078158516;
   fWeightMatrix0to1[15][15] = -2.936328717504;
   fWeightMatrix0to1[16][15] = 0.573271486643666;
   fWeightMatrix0to1[17][15] = -1.76472715208142;
   fWeightMatrix0to1[18][15] = -1.79672669013387;
   fWeightMatrix0to1[19][15] = -0.0583904025853827;
   fWeightMatrix0to1[20][15] = 1.19985081343201;
   fWeightMatrix0to1[0][16] = -0.216355021556714;
   fWeightMatrix0to1[1][16] = 0.882594713514943;
   fWeightMatrix0to1[2][16] = 0.392386777125741;
   fWeightMatrix0to1[3][16] = -0.0828447146432122;
   fWeightMatrix0to1[4][16] = -0.310208773735152;
   fWeightMatrix0to1[5][16] = 0.105818405159348;
   fWeightMatrix0to1[6][16] = 2.35419902312604;
   fWeightMatrix0to1[7][16] = -1.22062412121973;
   fWeightMatrix0to1[8][16] = 0.187525096264831;
   fWeightMatrix0to1[9][16] = -1.7294157148961;
   fWeightMatrix0to1[10][16] = -0.538178384335557;
   fWeightMatrix0to1[11][16] = 0.0924796401077921;
   fWeightMatrix0to1[12][16] = 0.101540433851643;
   fWeightMatrix0to1[13][16] = -0.575153669809154;
   fWeightMatrix0to1[14][16] = 1.21466137545433;
   fWeightMatrix0to1[15][16] = 1.98543996952865;
   fWeightMatrix0to1[16][16] = 0.886800639410771;
   fWeightMatrix0to1[17][16] = -0.0564816106097204;
   fWeightMatrix0to1[18][16] = -0.909767443829473;
   fWeightMatrix0to1[19][16] = -1.50679226279714;
   fWeightMatrix0to1[20][16] = -1.85604905039737;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.283513932542592;
   fWeightMatrix1to2[0][1] = -0.024607850520681;
   fWeightMatrix1to2[0][2] = 0.016927631030333;
   fWeightMatrix1to2[0][3] = -0.0274019968380435;
   fWeightMatrix1to2[0][4] = -0.0492309417090695;
   fWeightMatrix1to2[0][5] = 0.0123552742161398;
   fWeightMatrix1to2[0][6] = -1.1267751961675;
   fWeightMatrix1to2[0][7] = 0.0312132741528609;
   fWeightMatrix1to2[0][8] = -0.026469411758746;
   fWeightMatrix1to2[0][9] = -0.0735783171840853;
   fWeightMatrix1to2[0][10] = -0.0106198681104557;
   fWeightMatrix1to2[0][11] = -0.00741675917942956;
   fWeightMatrix1to2[0][12] = 0.0148108481768406;
   fWeightMatrix1to2[0][13] = 0.0951062795154336;
   fWeightMatrix1to2[0][14] = -0.078052890676334;
   fWeightMatrix1to2[0][15] = -0.257534834163047;
   fWeightMatrix1to2[0][16] = 0.0154733984376902;
   fWeightMatrix1to2[0][17] = 0.0358087522045106;
   fWeightMatrix1to2[0][18] = -0.0613085848257478;
   fWeightMatrix1to2[0][19] = 0.0053925493898634;
   fWeightMatrix1to2[0][20] = 0.424483742570244;
   fWeightMatrix1to2[0][21] = 1.98903551086983;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = -950;
   fMax_1[0][0] = 950;
   fMin_1[1][0] = -949.970336914;
   fMax_1[1][0] = 950;
   fMin_1[2][0] = -950;
   fMax_1[2][0] = 950;
   fMin_1[0][1] = 13.6949520111;
   fMax_1[0][1] = 1246.93212891;
   fMin_1[1][1] = 24.5881710052;
   fMax_1[1][1] = 1246.92883301;
   fMin_1[2][1] = 13.6949520111;
   fMax_1[2][1] = 1246.93212891;
   fMin_1[0][2] = -0.824912548065;
   fMax_1[0][2] = 0.999989211559;
   fMin_1[1][2] = -0.99983215332;
   fMax_1[1][2] = 0.996764361858;
   fMin_1[2][2] = -0.99983215332;
   fMax_1[2][2] = 0.999989211559;
   fMin_1[0][3] = -0.997001230717;
   fMax_1[0][3] = 0.971948325634;
   fMin_1[1][3] = -0.971729576588;
   fMax_1[1][3] = 0.995773375034;
   fMin_1[2][3] = -0.997001230717;
   fMax_1[2][3] = 0.995773375034;
   fMin_1[0][4] = -0.996843695641;
   fMax_1[0][4] = 0.985570847988;
   fMin_1[1][4] = -0.999999940395;
   fMax_1[1][4] = 0.531475186348;
   fMin_1[2][4] = -0.999999940395;
   fMax_1[2][4] = 0.985570847988;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 1;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 1;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 1;
   fMin_1[0][6] = 0;
   fMax_1[0][6] = 1;
   fMin_1[1][6] = 0;
   fMax_1[1][6] = 1;
   fMin_1[2][6] = 0;
   fMax_1[2][6] = 1;
   fMin_1[0][7] = 50;
   fMax_1[0][7] = 1263;
   fMin_1[1][7] = 50;
   fMax_1[1][7] = 1910;
   fMin_1[2][7] = 50;
   fMax_1[2][7] = 1910;
   fMin_1[0][8] = 500;
   fMax_1[0][8] = 4999.99804688;
   fMin_1[1][8] = 500;
   fMax_1[1][8] = 5000;
   fMin_1[2][8] = 500;
   fMax_1[2][8] = 5000;
   fMin_1[0][9] = 0.0041483649984;
   fMax_1[0][9] = 6.77362728119;
   fMin_1[1][9] = 0.00437234109268;
   fMax_1[1][9] = 2.74470567703;
   fMin_1[2][9] = 0.0041483649984;
   fMax_1[2][9] = 6.77362728119;
   fMin_1[0][10] = 0;
   fMax_1[0][10] = 0.995039105415;
   fMin_1[1][10] = 0;
   fMax_1[1][10] = 0.977042853832;
   fMin_1[2][10] = 0;
   fMax_1[2][10] = 0.995039105415;
   fMin_1[0][11] = 0;
   fMax_1[0][11] = 1;
   fMin_1[1][11] = 0.0108720073476;
   fMax_1[1][11] = 1;
   fMin_1[2][11] = 0;
   fMax_1[2][11] = 1;
   fMin_1[0][12] = 0;
   fMax_1[0][12] = 1;
   fMin_1[1][12] = 0;
   fMax_1[1][12] = 0.852035880089;
   fMin_1[2][12] = 0;
   fMax_1[2][12] = 1;
   fMin_1[0][13] = 0;
   fMax_1[0][13] = 0.985714256763;
   fMin_1[1][13] = 0;
   fMax_1[1][13] = 0.971291840076;
   fMin_1[2][13] = 0;
   fMax_1[2][13] = 0.985714256763;
   fMin_1[0][14] = 0;
   fMax_1[0][14] = 1;
   fMin_1[1][14] = 0.0154015403241;
   fMax_1[1][14] = 1;
   fMin_1[2][14] = 0;
   fMax_1[2][14] = 1;
   fMin_1[0][15] = 0;
   fMax_1[0][15] = 1;
   fMin_1[1][15] = 0;
   fMax_1[1][15] = 0.833333313465;
   fMin_1[2][15] = 0;
   fMax_1[2][15] = 1;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 16;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesGet.push_back( 14);
   indicesGet.push_back( 15);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);
   indicesPut.push_back( 14);
   indicesPut.push_back( 15);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<16;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
