// Class: ReadMLP
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : MLP::MLP
TMVA Release   : 4.1.2         [262402]
ROOT Release   : 5.30/00       [335360]
Creator        : jtingey
Date           : Mon Mar 12 14:17:39 2018
Host           : Linux pc143.hep.ucl.ac.uk 2.6.18-308.11.1.el5 #1 SMP Tue Jul 10 15:47:47 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /unix/chips/jtingey/CHIPS/code/WCSimAnalysis/pid/cosmicPid
Training events: 583
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
NCycles: "600" [Number of training cycles]
HiddenLayers: "N+5" [Specification of hidden layer architecture]
NeuronType: "tanh" [Neuron activation function type]
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VarTransform: "N" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "True" [Print method-specific help message]
TestRate: "5" [Test for overtraining performed at each #th epochs]
# Default:
RandomSeed: "1" [Random seed for initial synapse weights (0 means unique seed for each run; default value '1')]
EstimatorType: "MSE" [MSE (Mean Square Estimator) for Gaussian Likelihood or CE(Cross-Entropy) for Bernoulli Likelihood]
NeuronInputType: "sum" [Neuron input function type]
VerbosityLevel: "Default" [Verbosity level]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
TrainingMethod: "BP" [Train with Back-Propagation (BP), BFGS Algorithm (BFGS), or Genetic Algorithm (GA - slower and worse)]
LearningRate: "2.000000e-02" [ANN learning rate parameter]
DecayRate: "1.000000e-02" [Decay rate for learning parameter]
EpochMonitoring: "False" [Provide epoch-wise monitoring plots according to TestRate (caution: causes big ROOT output file!)]
Sampling: "1.000000e+00" [Only 'Sampling' (randomly selected) events are trained each epoch]
SamplingEpoch: "1.000000e+00" [Sampling is used for the first 'SamplingEpoch' epochs, afterwards, all events are taken for training]
SamplingImportance: "1.000000e+00" [ The sampling weights of events in epochs which successful (worse estimator than before) are multiplied with SamplingImportance, else they are divided.]
SamplingTraining: "True" [The training sample is sampled]
SamplingTesting: "False" [The testing sample is sampled]
ResetStep: "50" [How often BFGS should reset history]
Tau: "3.000000e+00" [LineSearch "size step"]
BPMode: "sequential" [Back-propagation learning mode: sequential or batch]
BatchSize: "-1" [Batch size: number of events/batch, only set if in Batch Mode, -1 for BatchSize=number_of_events]
ConvergenceImprove: "1.000000e-30" [Minimum improvement which counts as improvement (<0 means automatic convergence check is turned off)]
ConvergenceTests: "-1" [Number of steps (without improvement) required for convergence (<0 means automatic convergence check is turned off)]
UseRegulator: "False" [Use regulator to avoid over-training]
UpdateLimit: "10000" [Maximum times of regulator update]
CalculateErrors: "False" [Calculates inverse Hessian matrix at the end of the training to be able to calculate the uncertainties of an MVA value]
WeightRange: "1.000000e+00" [Take the events for the estimator calculations from small deviations from the desired value to large deviations only over the weight range]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 17
fNVetoHits                    fNVetoHits                    fNVetoHits                    fNVetoHits                                                      'F'    [0,49]
fNHits                        fNHits                        fNHits                        fNHits                                                          'F'    [51,1443]
fFracHitsUpstream             fFracHitsUpstream             fFracHitsUpstream             fFracHitsUpstream                                               'F'    [0,1]
fFracHitsDownstream           fFracHitsDownstream           fFracHitsDownstream           fFracHitsDownstream                                             'F'    [0,1]
fFracHitsAboveMid             fFracHitsAboveMid             fFracHitsAboveMid             fFracHitsAboveMid                                               'F'    [0,1]
fFracHitsBelowMid             fFracHitsBelowMid             fFracHitsBelowMid             fFracHitsBelowMid                                               'F'    [0,1]
fFracNHitsInRing              fFracNHitsInRing              fFracNHitsInRing              fFracNHitsInRing                                                'F'    [0.015625,0.836565077305]
fFracNHitsOutsideRing         fFracNHitsOutsideRing         fFracNHitsOutsideRing         fFracNHitsOutsideRing                                           'F'    [0,0.782608687878]
fFracNHitsInRingHole          fFracNHitsInRingHole          fFracNHitsInRingHole          fFracNHitsInRingHole                                            'F'    [0.104477614164,0.980392158031]
fEnergy                       fEnergy                       fEnergy                       fEnergy                                                         'F'    [550.075561523,4502.14648438]
fVtxX                         fVtxX                         fVtxX                         fVtxX                                                           'F'    [-1189.02636719,1194.78503418]
fVtxY                         fVtxY                         fVtxY                         fVtxY                                                           'F'    [-1199.47253418,1199.72705078]
fVtxZ                         fVtxZ                         fVtxZ                         fVtxZ                                                           'F'    [-449.342773438,447.003753662]
fVtxRho                       fVtxRho                       fVtxRho                       fVtxRho                                                         'F'    [40.132232666,1199.73376465]
fDirX                         fDirX                         fDirX                         fDirX                                                           'F'    [-0.999958515167,0.999891936779]
fDirY                         fDirY                         fDirY                         fDirY                                                           'F'    [-0.942760109901,0.998311877251]
fDirZ                         fDirZ                         fDirZ                         fDirZ                                                           'F'    [-0.970476090908,0.977583765984]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadMLP : public IClassifierReader {

 public:

   // constructor
   ReadMLP( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadMLP" ),
        fNvars( 17 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "fNVetoHits", "fNHits", "fFracHitsUpstream", "fFracHitsDownstream", "fFracHitsAboveMid", "fFracHitsBelowMid", "fFracNHitsInRing", "fFracNHitsOutsideRing", "fFracNHitsInRingHole", "fEnergy", "fVtxX", "fVtxY", "fVtxZ", "fVtxRho", "fDirX", "fDirY", "fDirZ" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -1;
      fVmax[0] = 1;
      fVmin[1] = -1;
      fVmax[1] = 1;
      fVmin[2] = -1;
      fVmax[2] = 1;
      fVmin[3] = -1;
      fVmax[3] = 1;
      fVmin[4] = -1;
      fVmax[4] = 1;
      fVmin[5] = -1;
      fVmax[5] = 1;
      fVmin[6] = -1;
      fVmax[6] = 1;
      fVmin[7] = -1;
      fVmax[7] = 1;
      fVmin[8] = -1;
      fVmax[8] = 0.99999988079071;
      fVmin[9] = -1;
      fVmax[9] = 1;
      fVmin[10] = -1;
      fVmax[10] = 0.99999988079071;
      fVmin[11] = -1;
      fVmax[11] = 1;
      fVmin[12] = -1;
      fVmax[12] = 1;
      fVmin[13] = -1;
      fVmax[13] = 1;
      fVmin[14] = -1;
      fVmax[14] = 1;
      fVmin[15] = -1;
      fVmax[15] = 0.99999988079071;
      fVmin[16] = -1;
      fVmax[16] = 1;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';

      // initialize constants
      Initialize();

      // initialize transformation
      InitTransform();
   }

   // destructor
   virtual ~ReadMLP() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // input variable transformation

   double fMin_1[3][17];
   double fMax_1[3][17];
   void InitTransform_1();
   void Transform_1( std::vector<double> & iv, int sigOrBgd ) const;
   void InitTransform();
   void Transform( std::vector<double> & iv, int sigOrBgd ) const;

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[17];
   double fVmax[17];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[17];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)

   double ActivationFnc(double x) const;
   double OutputActivationFnc(double x) const;

   int fLayers;
   int fLayerSize[3];
   double fWeightMatrix0to1[23][18];   // weight matrix from layer 0 to 1
   double fWeightMatrix1to2[1][23];   // weight matrix from layer 1 to 2

   double * fWeights[3];
};

inline void ReadMLP::Initialize()
{
   // build network structure
   fLayers = 3;
   fLayerSize[0] = 18; fWeights[0] = new double[18]; 
   fLayerSize[1] = 23; fWeights[1] = new double[23]; 
   fLayerSize[2] = 1; fWeights[2] = new double[1]; 
   // weight matrix from layer 0 to 1
   fWeightMatrix0to1[0][0] = -0.0275079035145904;
   fWeightMatrix0to1[1][0] = 2.15289711333377;
   fWeightMatrix0to1[2][0] = 1.62847537079969;
   fWeightMatrix0to1[3][0] = 1.7294948978598;
   fWeightMatrix0to1[4][0] = -1.87816043486025;
   fWeightMatrix0to1[5][0] = -1.29573128436304;
   fWeightMatrix0to1[6][0] = -0.844797738122261;
   fWeightMatrix0to1[7][0] = 1.98586006850337;
   fWeightMatrix0to1[8][0] = -1.25922023110443;
   fWeightMatrix0to1[9][0] = -1.45214665951752;
   fWeightMatrix0to1[10][0] = -1.57273026697665;
   fWeightMatrix0to1[11][0] = -0.306481024908789;
   fWeightMatrix0to1[12][0] = -1.38272898786295;
   fWeightMatrix0to1[13][0] = -0.686565430232101;
   fWeightMatrix0to1[14][0] = -0.642577047331251;
   fWeightMatrix0to1[15][0] = 0.714845560562784;
   fWeightMatrix0to1[16][0] = -0.45671860493602;
   fWeightMatrix0to1[17][0] = 1.56309287736603;
   fWeightMatrix0to1[18][0] = 0.205351122764895;
   fWeightMatrix0to1[19][0] = 1.23316306821345;
   fWeightMatrix0to1[20][0] = -0.100865408300267;
   fWeightMatrix0to1[21][0] = -0.610592872115119;
   fWeightMatrix0to1[0][1] = 0.755499156625844;
   fWeightMatrix0to1[1][1] = 0.296440168967352;
   fWeightMatrix0to1[2][1] = -0.792719827923637;
   fWeightMatrix0to1[3][1] = -0.258131917406614;
   fWeightMatrix0to1[4][1] = 1.76905729522285;
   fWeightMatrix0to1[5][1] = -1.10204987054183;
   fWeightMatrix0to1[6][1] = -1.73167960328193;
   fWeightMatrix0to1[7][1] = 0.0114440390597941;
   fWeightMatrix0to1[8][1] = 0.691186864046179;
   fWeightMatrix0to1[9][1] = 1.41088291649703;
   fWeightMatrix0to1[10][1] = -0.316361498613529;
   fWeightMatrix0to1[11][1] = 0.156911238119844;
   fWeightMatrix0to1[12][1] = 0.136237953950288;
   fWeightMatrix0to1[13][1] = -0.572132085745787;
   fWeightMatrix0to1[14][1] = -1.45141836833267;
   fWeightMatrix0to1[15][1] = 1.85426896926451;
   fWeightMatrix0to1[16][1] = -1.2275485637581;
   fWeightMatrix0to1[17][1] = 0.821427556442682;
   fWeightMatrix0to1[18][1] = 1.23567433047328;
   fWeightMatrix0to1[19][1] = 0.852925510681052;
   fWeightMatrix0to1[20][1] = 1.93226584268697;
   fWeightMatrix0to1[21][1] = 1.25289371587064;
   fWeightMatrix0to1[0][2] = -0.659357616883509;
   fWeightMatrix0to1[1][2] = -1.64241393234176;
   fWeightMatrix0to1[2][2] = 1.25922776518575;
   fWeightMatrix0to1[3][2] = 0.0832845866156494;
   fWeightMatrix0to1[4][2] = 1.3747064524502;
   fWeightMatrix0to1[5][2] = 1.53424544150321;
   fWeightMatrix0to1[6][2] = 1.510901467017;
   fWeightMatrix0to1[7][2] = 1.28426863003654;
   fWeightMatrix0to1[8][2] = -1.25513030359021;
   fWeightMatrix0to1[9][2] = 1.20019969819571;
   fWeightMatrix0to1[10][2] = -1.82744173026824;
   fWeightMatrix0to1[11][2] = -0.706356734960224;
   fWeightMatrix0to1[12][2] = -1.35332202019037;
   fWeightMatrix0to1[13][2] = -1.86648637575847;
   fWeightMatrix0to1[14][2] = 1.49779878952626;
   fWeightMatrix0to1[15][2] = 0.903870634047372;
   fWeightMatrix0to1[16][2] = -1.66987343866802;
   fWeightMatrix0to1[17][2] = 0.973097408700547;
   fWeightMatrix0to1[18][2] = -0.293581826242789;
   fWeightMatrix0to1[19][2] = 0.550180287211214;
   fWeightMatrix0to1[20][2] = 2.19760630003627;
   fWeightMatrix0to1[21][2] = -0.453646093675262;
   fWeightMatrix0to1[0][3] = 0.0457155149202367;
   fWeightMatrix0to1[1][3] = -1.19617925083549;
   fWeightMatrix0to1[2][3] = 0.277571136617384;
   fWeightMatrix0to1[3][3] = -0.852155816553473;
   fWeightMatrix0to1[4][3] = -0.607087321052271;
   fWeightMatrix0to1[5][3] = -1.50568391960303;
   fWeightMatrix0to1[6][3] = 0.813528887553844;
   fWeightMatrix0to1[7][3] = 1.16557690402208;
   fWeightMatrix0to1[8][3] = 0.933809834824582;
   fWeightMatrix0to1[9][3] = -0.231630858266124;
   fWeightMatrix0to1[10][3] = -1.94318601551917;
   fWeightMatrix0to1[11][3] = -2.0647581125904;
   fWeightMatrix0to1[12][3] = 1.03322095928435;
   fWeightMatrix0to1[13][3] = 0.599579096397962;
   fWeightMatrix0to1[14][3] = 1.97021557768147;
   fWeightMatrix0to1[15][3] = 0.420784423904723;
   fWeightMatrix0to1[16][3] = 1.05592339661527;
   fWeightMatrix0to1[17][3] = -1.40685414684602;
   fWeightMatrix0to1[18][3] = -0.900211722738107;
   fWeightMatrix0to1[19][3] = -0.0790259182159443;
   fWeightMatrix0to1[20][3] = 0.791069157230065;
   fWeightMatrix0to1[21][3] = -1.01070419627825;
   fWeightMatrix0to1[0][4] = -1.65659092249591;
   fWeightMatrix0to1[1][4] = -1.72790068214681;
   fWeightMatrix0to1[2][4] = 0.0449150963620594;
   fWeightMatrix0to1[3][4] = -0.123205215466482;
   fWeightMatrix0to1[4][4] = 1.54725645674472;
   fWeightMatrix0to1[5][4] = -1.65732077961543;
   fWeightMatrix0to1[6][4] = -0.722536693009246;
   fWeightMatrix0to1[7][4] = 1.62947064881904;
   fWeightMatrix0to1[8][4] = -0.365528553899981;
   fWeightMatrix0to1[9][4] = -1.55450143562565;
   fWeightMatrix0to1[10][4] = -1.45671349473224;
   fWeightMatrix0to1[11][4] = 0.444375648078487;
   fWeightMatrix0to1[12][4] = -1.92671532988694;
   fWeightMatrix0to1[13][4] = -1.57924078275056;
   fWeightMatrix0to1[14][4] = 0.704809031923951;
   fWeightMatrix0to1[15][4] = 1.49995173981196;
   fWeightMatrix0to1[16][4] = -1.13505510615125;
   fWeightMatrix0to1[17][4] = 1.64959576018707;
   fWeightMatrix0to1[18][4] = -0.926690151282556;
   fWeightMatrix0to1[19][4] = -0.817381757645008;
   fWeightMatrix0to1[20][4] = 0.190653577850242;
   fWeightMatrix0to1[21][4] = 0.365839594330113;
   fWeightMatrix0to1[0][5] = -1.71705485234671;
   fWeightMatrix0to1[1][5] = 0.28500549920101;
   fWeightMatrix0to1[2][5] = 0.0431294563104691;
   fWeightMatrix0to1[3][5] = 0.45591258416152;
   fWeightMatrix0to1[4][5] = -1.32596013831624;
   fWeightMatrix0to1[5][5] = 1.86815246407774;
   fWeightMatrix0to1[6][5] = 0.254215414643957;
   fWeightMatrix0to1[7][5] = -0.972074049027903;
   fWeightMatrix0to1[8][5] = 0.315663377061593;
   fWeightMatrix0to1[9][5] = -1.04347500674927;
   fWeightMatrix0to1[10][5] = -1.61383449929056;
   fWeightMatrix0to1[11][5] = -0.211384141579643;
   fWeightMatrix0to1[12][5] = -0.339592893724904;
   fWeightMatrix0to1[13][5] = 1.71348534487117;
   fWeightMatrix0to1[14][5] = 0.78813372385582;
   fWeightMatrix0to1[15][5] = 0.13973197118751;
   fWeightMatrix0to1[16][5] = -0.361715385475913;
   fWeightMatrix0to1[17][5] = 0.154599755488476;
   fWeightMatrix0to1[18][5] = -1.81130938384894;
   fWeightMatrix0to1[19][5] = 1.07504262828218;
   fWeightMatrix0to1[20][5] = -0.0807753027073939;
   fWeightMatrix0to1[21][5] = -1.84690020006377;
   fWeightMatrix0to1[0][6] = 0.607007165850081;
   fWeightMatrix0to1[1][6] = -1.39447657799148;
   fWeightMatrix0to1[2][6] = -0.198387976987391;
   fWeightMatrix0to1[3][6] = 1.15080842584118;
   fWeightMatrix0to1[4][6] = 1.99367587911647;
   fWeightMatrix0to1[5][6] = -2.01515490077477;
   fWeightMatrix0to1[6][6] = 0.360835576741114;
   fWeightMatrix0to1[7][6] = 1.51600187858951;
   fWeightMatrix0to1[8][6] = 1.47660041420111;
   fWeightMatrix0to1[9][6] = 0.12889441747793;
   fWeightMatrix0to1[10][6] = -1.44959148967735;
   fWeightMatrix0to1[11][6] = -0.453873035807006;
   fWeightMatrix0to1[12][6] = -1.46586238931211;
   fWeightMatrix0to1[13][6] = 1.44097831057376;
   fWeightMatrix0to1[14][6] = 1.22059035239874;
   fWeightMatrix0to1[15][6] = -0.447922599579297;
   fWeightMatrix0to1[16][6] = -0.360955371632458;
   fWeightMatrix0to1[17][6] = -0.191533382011495;
   fWeightMatrix0to1[18][6] = -1.31559070768853;
   fWeightMatrix0to1[19][6] = 0.662033677322396;
   fWeightMatrix0to1[20][6] = 1.17674735140747;
   fWeightMatrix0to1[21][6] = -0.492797526505845;
   fWeightMatrix0to1[0][7] = -0.592777254656386;
   fWeightMatrix0to1[1][7] = 0.237798131477616;
   fWeightMatrix0to1[2][7] = 1.45892693251514;
   fWeightMatrix0to1[3][7] = 0.559872169590622;
   fWeightMatrix0to1[4][7] = 0.67015914115672;
   fWeightMatrix0to1[5][7] = -1.37050862297547;
   fWeightMatrix0to1[6][7] = 1.57456874473359;
   fWeightMatrix0to1[7][7] = 0.723169540516718;
   fWeightMatrix0to1[8][7] = 0.565414871701509;
   fWeightMatrix0to1[9][7] = 0.523903329219068;
   fWeightMatrix0to1[10][7] = 1.00665206674628;
   fWeightMatrix0to1[11][7] = -0.174917926112857;
   fWeightMatrix0to1[12][7] = -0.610074937431205;
   fWeightMatrix0to1[13][7] = 1.00400892902062;
   fWeightMatrix0to1[14][7] = -0.926350606982161;
   fWeightMatrix0to1[15][7] = -0.404144704518045;
   fWeightMatrix0to1[16][7] = 1.53251304902725;
   fWeightMatrix0to1[17][7] = 1.44498585568017;
   fWeightMatrix0to1[18][7] = -0.295988870623695;
   fWeightMatrix0to1[19][7] = 1.46161829134504;
   fWeightMatrix0to1[20][7] = 2.41856081341503;
   fWeightMatrix0to1[21][7] = -2.03423776901494;
   fWeightMatrix0to1[0][8] = 0.690977543124643;
   fWeightMatrix0to1[1][8] = 0.0299218918024005;
   fWeightMatrix0to1[2][8] = 0.935181751320679;
   fWeightMatrix0to1[3][8] = -1.69212126083854;
   fWeightMatrix0to1[4][8] = -1.63972886506201;
   fWeightMatrix0to1[5][8] = 1.18694251689314;
   fWeightMatrix0to1[6][8] = 1.90911075757826;
   fWeightMatrix0to1[7][8] = -1.75941061231647;
   fWeightMatrix0to1[8][8] = -0.0292088149163254;
   fWeightMatrix0to1[9][8] = -0.726540998561673;
   fWeightMatrix0to1[10][8] = 0.319438136430439;
   fWeightMatrix0to1[11][8] = 2.32651214747287;
   fWeightMatrix0to1[12][8] = -0.436761155606087;
   fWeightMatrix0to1[13][8] = -0.611661079954187;
   fWeightMatrix0to1[14][8] = -1.07653270821324;
   fWeightMatrix0to1[15][8] = 1.06539708994904;
   fWeightMatrix0to1[16][8] = 1.55631664722843;
   fWeightMatrix0to1[17][8] = 1.44770113741233;
   fWeightMatrix0to1[18][8] = 0.341835269513046;
   fWeightMatrix0to1[19][8] = -0.865671597325948;
   fWeightMatrix0to1[20][8] = -1.15423471750922;
   fWeightMatrix0to1[21][8] = 1.08116564544629;
   fWeightMatrix0to1[0][9] = 0.50856794058697;
   fWeightMatrix0to1[1][9] = -1.19547386931787;
   fWeightMatrix0to1[2][9] = -0.307531433485857;
   fWeightMatrix0to1[3][9] = 0.294544085091815;
   fWeightMatrix0to1[4][9] = 0.31605451661151;
   fWeightMatrix0to1[5][9] = -1.92979637076347;
   fWeightMatrix0to1[6][9] = 1.62984607337921;
   fWeightMatrix0to1[7][9] = 0.695205923345611;
   fWeightMatrix0to1[8][9] = -0.609446693006975;
   fWeightMatrix0to1[9][9] = -0.378476450787139;
   fWeightMatrix0to1[10][9] = 1.67039220343313;
   fWeightMatrix0to1[11][9] = 1.36023602999461;
   fWeightMatrix0to1[12][9] = 0.394174623048196;
   fWeightMatrix0to1[13][9] = -0.415199984276727;
   fWeightMatrix0to1[14][9] = -1.95179029564638;
   fWeightMatrix0to1[15][9] = -0.810016838792752;
   fWeightMatrix0to1[16][9] = 1.68821641944957;
   fWeightMatrix0to1[17][9] = 1.1308608345844;
   fWeightMatrix0to1[18][9] = 0.79364809066217;
   fWeightMatrix0to1[19][9] = 0.176193421487728;
   fWeightMatrix0to1[20][9] = 1.90453382923906;
   fWeightMatrix0to1[21][9] = -1.68301347206347;
   fWeightMatrix0to1[0][10] = -1.32139404271481;
   fWeightMatrix0to1[1][10] = -0.174515765864516;
   fWeightMatrix0to1[2][10] = -1.16776245262284;
   fWeightMatrix0to1[3][10] = 0.961491176247405;
   fWeightMatrix0to1[4][10] = 1.36360861264152;
   fWeightMatrix0to1[5][10] = -1.22419537816349;
   fWeightMatrix0to1[6][10] = 0.858894148041388;
   fWeightMatrix0to1[7][10] = -0.189074187655074;
   fWeightMatrix0to1[8][10] = -2.29687227222264;
   fWeightMatrix0to1[9][10] = -1.28192153702865;
   fWeightMatrix0to1[10][10] = 1.04498348942613;
   fWeightMatrix0to1[11][10] = 0.755232319684148;
   fWeightMatrix0to1[12][10] = 0.968002991546876;
   fWeightMatrix0to1[13][10] = -1.28837932254268;
   fWeightMatrix0to1[14][10] = 1.65866138585852;
   fWeightMatrix0to1[15][10] = -1.87970078147688;
   fWeightMatrix0to1[16][10] = 0.831239203778361;
   fWeightMatrix0to1[17][10] = 0.429635686393509;
   fWeightMatrix0to1[18][10] = -1.45388155581316;
   fWeightMatrix0to1[19][10] = -1.33553348047627;
   fWeightMatrix0to1[20][10] = -1.68767791555473;
   fWeightMatrix0to1[21][10] = -0.393904123201027;
   fWeightMatrix0to1[0][11] = -1.84128239755952;
   fWeightMatrix0to1[1][11] = -1.42525193652893;
   fWeightMatrix0to1[2][11] = -1.61413289647122;
   fWeightMatrix0to1[3][11] = 0.00374542995019666;
   fWeightMatrix0to1[4][11] = -0.937010528658901;
   fWeightMatrix0to1[5][11] = -1.631318738237;
   fWeightMatrix0to1[6][11] = 1.39255297409807;
   fWeightMatrix0to1[7][11] = -0.849538162984652;
   fWeightMatrix0to1[8][11] = 0.167936511588752;
   fWeightMatrix0to1[9][11] = -1.36090287600742;
   fWeightMatrix0to1[10][11] = 0.251147452625982;
   fWeightMatrix0to1[11][11] = 1.20060291843027;
   fWeightMatrix0to1[12][11] = 1.32465854424953;
   fWeightMatrix0to1[13][11] = -0.961876626506142;
   fWeightMatrix0to1[14][11] = -1.49973891127759;
   fWeightMatrix0to1[15][11] = -0.941884640603573;
   fWeightMatrix0to1[16][11] = -0.875770535408277;
   fWeightMatrix0to1[17][11] = -1.30941946900507;
   fWeightMatrix0to1[18][11] = 0.346852721664726;
   fWeightMatrix0to1[19][11] = 0.281312991544778;
   fWeightMatrix0to1[20][11] = 1.4209590823682;
   fWeightMatrix0to1[21][11] = -0.276273471479245;
   fWeightMatrix0to1[0][12] = 0.348145004211374;
   fWeightMatrix0to1[1][12] = -0.447453355594169;
   fWeightMatrix0to1[2][12] = -1.51964186967689;
   fWeightMatrix0to1[3][12] = 1.20939555606532;
   fWeightMatrix0to1[4][12] = 1.15427161877976;
   fWeightMatrix0to1[5][12] = -0.763476563236643;
   fWeightMatrix0to1[6][12] = -0.984848012821899;
   fWeightMatrix0to1[7][12] = 0.812701331680384;
   fWeightMatrix0to1[8][12] = 1.20397369905733;
   fWeightMatrix0to1[9][12] = 0.0599670215451709;
   fWeightMatrix0to1[10][12] = -0.429135356514154;
   fWeightMatrix0to1[11][12] = -0.43428159381454;
   fWeightMatrix0to1[12][12] = 1.39556820704213;
   fWeightMatrix0to1[13][12] = 0.983885609904149;
   fWeightMatrix0to1[14][12] = 0.967787953952395;
   fWeightMatrix0to1[15][12] = -0.416366922788141;
   fWeightMatrix0to1[16][12] = 0.272156421172654;
   fWeightMatrix0to1[17][12] = -0.790549207070127;
   fWeightMatrix0to1[18][12] = -1.42129292550244;
   fWeightMatrix0to1[19][12] = -0.523586976833183;
   fWeightMatrix0to1[20][12] = -1.18382983789582;
   fWeightMatrix0to1[21][12] = -1.22232368138176;
   fWeightMatrix0to1[0][13] = -1.57031524602383;
   fWeightMatrix0to1[1][13] = 1.74636389631573;
   fWeightMatrix0to1[2][13] = -1.93361023509845;
   fWeightMatrix0to1[3][13] = 1.684203361646;
   fWeightMatrix0to1[4][13] = -1.58812554823656;
   fWeightMatrix0to1[5][13] = 1.12914960892308;
   fWeightMatrix0to1[6][13] = -1.06079617668402;
   fWeightMatrix0to1[7][13] = 0.649448540635359;
   fWeightMatrix0to1[8][13] = 0.218232044597486;
   fWeightMatrix0to1[9][13] = -1.54094141199041;
   fWeightMatrix0to1[10][13] = 0.263411761437149;
   fWeightMatrix0to1[11][13] = -0.0558378398716398;
   fWeightMatrix0to1[12][13] = -1.86501228500195;
   fWeightMatrix0to1[13][13] = -1.30173212220823;
   fWeightMatrix0to1[14][13] = -1.67205612314963;
   fWeightMatrix0to1[15][13] = -0.933793151266409;
   fWeightMatrix0to1[16][13] = 1.8155277193117;
   fWeightMatrix0to1[17][13] = -1.00663287282598;
   fWeightMatrix0to1[18][13] = 0.206860326087658;
   fWeightMatrix0to1[19][13] = -0.883506632961411;
   fWeightMatrix0to1[20][13] = -1.49339100538773;
   fWeightMatrix0to1[21][13] = -1.77226823345807;
   fWeightMatrix0to1[0][14] = -1.11240265760287;
   fWeightMatrix0to1[1][14] = -1.41345515960277;
   fWeightMatrix0to1[2][14] = 0.33193150390433;
   fWeightMatrix0to1[3][14] = -1.35753914415041;
   fWeightMatrix0to1[4][14] = -0.789764646932945;
   fWeightMatrix0to1[5][14] = 1.62219859121821;
   fWeightMatrix0to1[6][14] = 0.316003339750577;
   fWeightMatrix0to1[7][14] = -0.44107547428129;
   fWeightMatrix0to1[8][14] = 2.20931800236497;
   fWeightMatrix0to1[9][14] = -1.4286362436444;
   fWeightMatrix0to1[10][14] = 1.3461865867336;
   fWeightMatrix0to1[11][14] = 0.246634280997045;
   fWeightMatrix0to1[12][14] = -0.946722021854651;
   fWeightMatrix0to1[13][14] = -0.574474799079889;
   fWeightMatrix0to1[14][14] = 0.0176125805398311;
   fWeightMatrix0to1[15][14] = -1.21078580476902;
   fWeightMatrix0to1[16][14] = 0.549538900003362;
   fWeightMatrix0to1[17][14] = 1.22967424154238;
   fWeightMatrix0to1[18][14] = 1.25672890551199;
   fWeightMatrix0to1[19][14] = 1.71078528824017;
   fWeightMatrix0to1[20][14] = -1.65972160824218;
   fWeightMatrix0to1[21][14] = 1.09623970112535;
   fWeightMatrix0to1[0][15] = -1.82761477674745;
   fWeightMatrix0to1[1][15] = 0.557091463567733;
   fWeightMatrix0to1[2][15] = -1.73501880677682;
   fWeightMatrix0to1[3][15] = -1.83586557667106;
   fWeightMatrix0to1[4][15] = 0.0312124960197624;
   fWeightMatrix0to1[5][15] = 1.22053242534348;
   fWeightMatrix0to1[6][15] = 0.357444732188912;
   fWeightMatrix0to1[7][15] = 1.0631416840445;
   fWeightMatrix0to1[8][15] = 0.261918390130865;
   fWeightMatrix0to1[9][15] = -0.336090949062202;
   fWeightMatrix0to1[10][15] = -0.755868640568435;
   fWeightMatrix0to1[11][15] = -0.100859370201282;
   fWeightMatrix0to1[12][15] = 1.96248331023621;
   fWeightMatrix0to1[13][15] = -1.43948071496661;
   fWeightMatrix0to1[14][15] = 0.318052277592247;
   fWeightMatrix0to1[15][15] = -1.30513249469582;
   fWeightMatrix0to1[16][15] = -0.450237053698759;
   fWeightMatrix0to1[17][15] = 0.105755464962757;
   fWeightMatrix0to1[18][15] = 0.208585665405898;
   fWeightMatrix0to1[19][15] = -1.16483996669864;
   fWeightMatrix0to1[20][15] = 0.905617960797722;
   fWeightMatrix0to1[21][15] = 1.68646299199532;
   fWeightMatrix0to1[0][16] = 0.578555281927369;
   fWeightMatrix0to1[1][16] = -0.20368819924261;
   fWeightMatrix0to1[2][16] = -0.923457304456954;
   fWeightMatrix0to1[3][16] = -1.45600803072011;
   fWeightMatrix0to1[4][16] = -1.77794361243731;
   fWeightMatrix0to1[5][16] = 1.07022926431941;
   fWeightMatrix0to1[6][16] = -0.461779795866729;
   fWeightMatrix0to1[7][16] = -1.13215168310185;
   fWeightMatrix0to1[8][16] = 0.958060973553481;
   fWeightMatrix0to1[9][16] = -1.47095989836454;
   fWeightMatrix0to1[10][16] = -1.13928849789239;
   fWeightMatrix0to1[11][16] = -1.17383926438626;
   fWeightMatrix0to1[12][16] = 1.0606159618079;
   fWeightMatrix0to1[13][16] = -1.18734792871517;
   fWeightMatrix0to1[14][16] = -1.72048899573123;
   fWeightMatrix0to1[15][16] = -0.641460067697128;
   fWeightMatrix0to1[16][16] = -0.961179811605595;
   fWeightMatrix0to1[17][16] = -1.45863202645612;
   fWeightMatrix0to1[18][16] = 1.18412945998854;
   fWeightMatrix0to1[19][16] = -1.42687620503677;
   fWeightMatrix0to1[20][16] = -1.30986545457404;
   fWeightMatrix0to1[21][16] = 1.67085401255595;
   fWeightMatrix0to1[0][17] = 0.549930581760402;
   fWeightMatrix0to1[1][17] = 0.258908563561705;
   fWeightMatrix0to1[2][17] = -0.648357293781845;
   fWeightMatrix0to1[3][17] = 1.35529086466268;
   fWeightMatrix0to1[4][17] = 1.82806574906029;
   fWeightMatrix0to1[5][17] = 0.463705617987798;
   fWeightMatrix0to1[6][17] = -1.1437313571018;
   fWeightMatrix0to1[7][17] = -0.623082489370319;
   fWeightMatrix0to1[8][17] = -1.86507946511767;
   fWeightMatrix0to1[9][17] = 1.20395507396327;
   fWeightMatrix0to1[10][17] = 0.929391807528633;
   fWeightMatrix0to1[11][17] = -0.754359370085901;
   fWeightMatrix0to1[12][17] = 1.20543170567886;
   fWeightMatrix0to1[13][17] = 1.30525205148934;
   fWeightMatrix0to1[14][17] = 1.67808382869259;
   fWeightMatrix0to1[15][17] = -1.58725644583541;
   fWeightMatrix0to1[16][17] = 1.79786419418531;
   fWeightMatrix0to1[17][17] = 0.230505169559615;
   fWeightMatrix0to1[18][17] = -2.01868439008011;
   fWeightMatrix0to1[19][17] = -0.197152888953437;
   fWeightMatrix0to1[20][17] = -2.07774133336717;
   fWeightMatrix0to1[21][17] = 0.94323202627769;
   // weight matrix from layer 1 to 2
   fWeightMatrix1to2[0][0] = 0.00554290956681983;
   fWeightMatrix1to2[0][1] = 0.00710597027723036;
   fWeightMatrix1to2[0][2] = 0.056504714746727;
   fWeightMatrix1to2[0][3] = 0.000656175063881201;
   fWeightMatrix1to2[0][4] = 0.00532967905481196;
   fWeightMatrix1to2[0][5] = 0.00262600532699616;
   fWeightMatrix1to2[0][6] = 0.0181323483191832;
   fWeightMatrix1to2[0][7] = -0.000762670855478705;
   fWeightMatrix1to2[0][8] = 0.526724711041038;
   fWeightMatrix1to2[0][9] = -0.00223674787797407;
   fWeightMatrix1to2[0][10] = -0.00779946240495281;
   fWeightMatrix1to2[0][11] = 1.15458516758297;
   fWeightMatrix1to2[0][12] = 0.00215129223016205;
   fWeightMatrix1to2[0][13] = -0.00774059321598505;
   fWeightMatrix1to2[0][14] = 0.00449522497719975;
   fWeightMatrix1to2[0][15] = -0.556573210158576;
   fWeightMatrix1to2[0][16] = -0.0175236156697998;
   fWeightMatrix1to2[0][17] = -0.208135440374246;
   fWeightMatrix1to2[0][18] = 0.00540822008099389;
   fWeightMatrix1to2[0][19] = -0.00223105060839381;
   fWeightMatrix1to2[0][20] = 0.115922085653242;
   fWeightMatrix1to2[0][21] = -0.00894416607452452;
   fWeightMatrix1to2[0][22] = 1.08941076485869;
}

inline double ReadMLP::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   if (inputValues.size() != (unsigned int)fLayerSize[0]-1) {
      std::cout << "Input vector needs to be of size " << fLayerSize[0]-1 << std::endl;
      return 0;
   }

   for (int l=0; l<fLayers; l++)
      for (int i=0; i<fLayerSize[l]; i++) fWeights[l][i]=0;

   for (int l=0; l<fLayers-1; l++)
      fWeights[l][fLayerSize[l]-1]=1;

   for (int i=0; i<fLayerSize[0]-1; i++)
      fWeights[0][i]=inputValues[i];

   // layer 0 to 1
   for (int o=0; o<fLayerSize[1]-1; o++) {
      for (int i=0; i<fLayerSize[0]; i++) {
         double inputVal = fWeightMatrix0to1[o][i] * fWeights[0][i];
         fWeights[1][o] += inputVal;
      }
      fWeights[1][o] = ActivationFnc(fWeights[1][o]);
   }
   // layer 1 to 2
   for (int o=0; o<fLayerSize[2]; o++) {
      for (int i=0; i<fLayerSize[1]; i++) {
         double inputVal = fWeightMatrix1to2[o][i] * fWeights[1][i];
         fWeights[2][o] += inputVal;
      }
      fWeights[2][o] = OutputActivationFnc(fWeights[2][o]);
   }

   return fWeights[2][0];
}

double ReadMLP::ActivationFnc(double x) const {
   // hyperbolic tan
   return tanh(x);
}
double ReadMLP::OutputActivationFnc(double x) const {
   // identity
   return x;
}
   
// Clean up
inline void ReadMLP::Clear() 
{
   // nothing to clear
}
   inline double ReadMLP::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
         else {
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(*varIt);
            }
            Transform( iV, -1 );
            retval = GetMvaValue__( iV );
         }
      }

      return retval;
   }

//_______________________________________________________________________
inline void ReadMLP::InitTransform_1()
{
   // Normalization transformation, initialisation
   fMin_1[0][0] = 0;
   fMax_1[0][0] = 49;
   fMin_1[1][0] = 3;
   fMax_1[1][0] = 49;
   fMin_1[2][0] = 0;
   fMax_1[2][0] = 49;
   fMin_1[0][1] = 51;
   fMax_1[0][1] = 1443;
   fMin_1[1][1] = 57;
   fMax_1[1][1] = 415;
   fMin_1[2][1] = 51;
   fMax_1[2][1] = 1443;
   fMin_1[0][2] = 0;
   fMax_1[0][2] = 0.553459107876;
   fMin_1[1][2] = 0;
   fMax_1[1][2] = 1;
   fMin_1[2][2] = 0;
   fMax_1[2][2] = 1;
   fMin_1[0][3] = 0.446540892124;
   fMax_1[0][3] = 1;
   fMin_1[1][3] = 0;
   fMax_1[1][3] = 1;
   fMin_1[2][3] = 0;
   fMax_1[2][3] = 1;
   fMin_1[0][4] = 0;
   fMax_1[0][4] = 1;
   fMin_1[1][4] = 0;
   fMax_1[1][4] = 1;
   fMin_1[2][4] = 0;
   fMax_1[2][4] = 1;
   fMin_1[0][5] = 0;
   fMax_1[0][5] = 1;
   fMin_1[1][5] = 0;
   fMax_1[1][5] = 1;
   fMin_1[2][5] = 0;
   fMax_1[2][5] = 1;
   fMin_1[0][6] = 0.0196078438312;
   fMax_1[0][6] = 0.836565077305;
   fMin_1[1][6] = 0.015625;
   fMax_1[1][6] = 0.786885261536;
   fMin_1[2][6] = 0.015625;
   fMax_1[2][6] = 0.836565077305;
   fMin_1[0][7] = 0;
   fMax_1[0][7] = 0.641509413719;
   fMin_1[1][7] = 0.0104166669771;
   fMax_1[1][7] = 0.782608687878;
   fMin_1[2][7] = 0;
   fMax_1[2][7] = 0.782608687878;
   fMin_1[0][8] = 0.117065124214;
   fMax_1[0][8] = 0.980392158031;
   fMin_1[1][8] = 0.104477614164;
   fMax_1[1][8] = 0.824561417103;
   fMin_1[2][8] = 0.104477614164;
   fMax_1[2][8] = 0.980392158031;
   fMin_1[0][9] = 552.730285645;
   fMax_1[0][9] = 4502.14648438;
   fMin_1[1][9] = 550.075561523;
   fMax_1[1][9] = 3436.98217773;
   fMin_1[2][9] = 550.075561523;
   fMax_1[2][9] = 4502.14648438;
   fMin_1[0][10] = -1189.02636719;
   fMax_1[0][10] = 940.280090332;
   fMin_1[1][10] = -453.735595703;
   fMax_1[1][10] = 1194.78503418;
   fMin_1[2][10] = -1189.02636719;
   fMax_1[2][10] = 1194.78503418;
   fMin_1[0][11] = -1199.47253418;
   fMax_1[0][11] = 1199.72705078;
   fMin_1[1][11] = -1008.44763184;
   fMax_1[1][11] = 977.824462891;
   fMin_1[2][11] = -1199.47253418;
   fMax_1[2][11] = 1199.72705078;
   fMin_1[0][12] = -449.342773438;
   fMax_1[0][12] = 447.003753662;
   fMin_1[1][12] = -449.128540039;
   fMax_1[1][12] = 445.425750732;
   fMin_1[2][12] = -449.342773438;
   fMax_1[2][12] = 447.003753662;
   fMin_1[0][13] = 40.132232666;
   fMax_1[0][13] = 1199.73376465;
   fMin_1[1][13] = 416.673187256;
   fMax_1[1][13] = 1199.66833496;
   fMin_1[2][13] = 40.132232666;
   fMax_1[2][13] = 1199.73376465;
   fMin_1[0][14] = -0.010506439954;
   fMax_1[0][14] = 0.999891936779;
   fMin_1[1][14] = -0.999958515167;
   fMax_1[1][14] = -0.057964220643;
   fMin_1[2][14] = -0.999958515167;
   fMax_1[2][14] = 0.999891936779;
   fMin_1[0][15] = -0.942760109901;
   fMax_1[0][15] = 0.904550671577;
   fMin_1[1][15] = -0.832851886749;
   fMax_1[1][15] = 0.998311877251;
   fMin_1[2][15] = -0.942760109901;
   fMax_1[2][15] = 0.998311877251;
   fMin_1[0][16] = -0.970476090908;
   fMax_1[0][16] = 0.977583765984;
   fMin_1[1][16] = -0.963372170925;
   fMax_1[1][16] = 0.938173770905;
   fMin_1[2][16] = -0.970476090908;
   fMax_1[2][16] = 0.977583765984;
}

//_______________________________________________________________________
inline void ReadMLP::Transform_1( std::vector<double>& iv, int cls) const
{
   // Normalization transformation
   if (cls < 0 || cls > 2) {
   if (2 > 1 ) cls = 2;
      else cls = 2;
   }
   const int nVar = 17;

   // get indices of used variables

   // define the indices of the variables which are transformed by this transformation
   std::vector<int> indicesGet;
   std::vector<int> indicesPut;

   indicesGet.push_back( 0);
   indicesGet.push_back( 1);
   indicesGet.push_back( 2);
   indicesGet.push_back( 3);
   indicesGet.push_back( 4);
   indicesGet.push_back( 5);
   indicesGet.push_back( 6);
   indicesGet.push_back( 7);
   indicesGet.push_back( 8);
   indicesGet.push_back( 9);
   indicesGet.push_back( 10);
   indicesGet.push_back( 11);
   indicesGet.push_back( 12);
   indicesGet.push_back( 13);
   indicesGet.push_back( 14);
   indicesGet.push_back( 15);
   indicesGet.push_back( 16);
   indicesPut.push_back( 0);
   indicesPut.push_back( 1);
   indicesPut.push_back( 2);
   indicesPut.push_back( 3);
   indicesPut.push_back( 4);
   indicesPut.push_back( 5);
   indicesPut.push_back( 6);
   indicesPut.push_back( 7);
   indicesPut.push_back( 8);
   indicesPut.push_back( 9);
   indicesPut.push_back( 10);
   indicesPut.push_back( 11);
   indicesPut.push_back( 12);
   indicesPut.push_back( 13);
   indicesPut.push_back( 14);
   indicesPut.push_back( 15);
   indicesPut.push_back( 16);

   std::vector<double> dv(nVar);
   for (int ivar=0; ivar<nVar; ivar++) dv[ivar] = iv[indicesGet.at(ivar)];
   for (int ivar=0;ivar<17;ivar++) {
      double offset = fMin_1[cls][ivar];
      double scale  = 1.0/(fMax_1[cls][ivar]-fMin_1[cls][ivar]);
      iv[indicesPut.at(ivar)] = (dv[ivar]-offset)*scale * 2 - 1;
   }
}

//_______________________________________________________________________
inline void ReadMLP::InitTransform()
{
   InitTransform_1();
}

//_______________________________________________________________________
inline void ReadMLP::Transform( std::vector<double>& iv, int sigOrBgd ) const
{
   Transform_1( iv, sigOrBgd );
}
